### ISSUE TITLE
Folder- and file icons not shown when QT_SCALE_FACTOR is set to 2

### ISSUE THREAD

**Issue by fjellvannet** [lxqt/pcmanfm-qt#834] opened 2018-12-05 16:39 UTC
##### Expected Behavior
Normally, when pcmanfm-qt is opened in the user-folder at QT_SCALE_FACTOR = 1, icons for the folders and files are shown. I'd expect these to be shown at QT_SCALE_FACTOR = 2 as well. 

##### Current Behavior
Right now, no icons are shown, it looks as if a transparent icon was loaded, as the space that would have been taken up by the icon is taken up. Folder icons in the side-tray show up correctly.

##### Steps to Reproduce (for bugs)
1. Download and install Lubuntu 18.10 amd64 in VMware Player
2. install open-vm-tools and open-vm-tools-desktop (in order to make the VM run properly)
3. set QT_SCALE_FACTOR to 2 (or sth. else != 1)
4. start pcmanfm-qt in your home folder

##### System Information

* Distribution & Version: Lubuntu 18.10
* Kernel: 4.18.0-12-generic
* Qt Version: 5 (it says 4 and 5 are installed, coudn't identify which one is used and whether it is Qt 5.7.0.)
* lxqt-build-tools Version: this package isn't installed (as far as I can see)
* libqtxdg Version: this package isn't installed (as far as I can see)
* libfm-qt Version: 0.13.1-5ubuntu7
* Package version: 0.13.0

**Comment by tsujan** [comment] 2018-12-05 16:51
Wow! You're right -- I had never tested it.

This should be fixed before the next release.

**Comment by tsujan** [comment] 2018-12-05 16:54
Worse than that: the problem is in libfm-qt.

**Comment by fjellvannet** [comment] 2018-12-05 17:03
Thank you mate!

You have done an amazing job today answering my questions (also in the forum ;))

**Comment by tsujan** [comment] 2018-12-05 19:16
OK, this is simply about `QIconEngine::ScaledPixmapHook`, which we forgot to add after Qt 5.9. But I may have found other hidden problems with icons. So, it may take a little longer to make a PR.

**Comment by tsujan** [comment] 2018-12-05 19:42
I opened https://github.com/lxqt/pcmanfm-qt/issues/835 for the other issues I found. They need a separate PR after the next release.

**Comment by tsujan** [comment] 2018-12-05 23:43
> Must have something to do with the qt svg rendering options set.

No! It's a problem in our `IconInfo` and happens with PNG icons too but *only when scaled*. After you reported this issue, I added an "obvious" fix to my installed libfm-qt, so that scaled icons were shown here. I wanted to make a PR but, fortunately, saw the mess ;) The real solution may not be as obvious as I thought.

**Comment by tsujan** [comment] 2018-12-06 01:31
Coming back to this after some rest:

The problem was NOT in my simple patch but in LXQt's `XdgIconLoaderEngine::virtual_hook()`. These are the blurry side-pane icons with `QT_SCALE_FACTOR=3 pcmanfm-qt` and the Breeze widget style under LXQt after patching:

![lxqt](https://user-images.githubusercontent.com/981076/49554912-0d70ef00-f913-11e8-8bd8-c736ff234551.png)

And these are the same side-pane icons of pcmanfm-qt with the same scaling factor, the same icon theme and the same patch but under KDE:

![kde](https://user-images.githubusercontent.com/981076/49554944-2a0d2700-f913-11e8-8106-05ee6441b22c.png)

KDE does it right in its `KIconEngine::virtual_hook()`.

**Closed** 2018-12-14 23:51 UTC
Labels: bug, release-blocker
