### ISSUE TITLE
Multiple KDE applications in pcmanfm-qt "Applications"

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1403] opened 2021-06-18 05:10 UTC
Stumbled upon that testing the fix for https://github.com/lxqt/pcmanfm-qt/issues/1401

Okular and Marble show multiple files in "Applications":
![schermata-07-01-56](https://user-images.githubusercontent.com/10681413/122509132-8c2a6500-d003-11eb-8324-c44b32320a6c.png)

![schermata-06-57-22](https://user-images.githubusercontent.com/10681413/122509140-9187af80-d003-11eb-82ea-af4cc9c15c19.png)

```
ls /usr/share/applications/ |grep marble
marble_geojson.desktop
marble_gpx.desktop
marble_kml.desktop
marble_kmz.desktop
marble_shp.desktop
```

  In the   panel's menu only one is shown.

##### Expected Behavior

Similar as in the menu only one should be shown
##### System Information

* Distribution & Version: all, git master

**Comment by tsujan** [comment] 2021-06-18 10:08
Yes but the problem is deeper. See https://github.com/lxqt/libfm-qt/issues/417

I close this not because it isn't valid but because a more fundamental change is needed.

**Closed by tsujan** 2021-06-18 10:08 UTC

**Comment by stefonarch** [comment] 2021-06-18 10:35
I just wonder why KDE need tons of okular.desktop but anyway - I hardly ever look  in  `menu://applications/`

**Comment by tsujan** [comment] 2021-06-18 10:44
Oh, I think this isn't a bug. All those items in your screenshot have italic texts. It means they **are** hidden. Do you show hidden files under `menu://applications/`?

**Comment by tsujan** [comment] 2021-06-18 10:49
This is correct (see Krita icons):

![hidden](https://user-images.githubusercontent.com/981076/122550088-7f7c3000-d048-11eb-8476-bc23d300d7e2.png)

**Comment by tsujan** [comment] 2021-06-18 10:57
> I just wonder why KDE need tons of okular.desktop

If you go to /usr/share/applications and drop them into a text editor, you'll see the differences between them. I'd say KDE does a weird thing but since it adds `NoDisplay=true` to them, there's no problem.

**Comment by stefonarch** [comment] 2021-06-18 10:59
You'r right, for some reason "show hidden" was set there. So no issue, but I didn't think about hidden files there   to be honest :)

**Comment by tsujan** [comment] 2021-06-18 11:06
Probably, you wanted to test the recursive customization there and showed hidden files under `menu://applications/`.

I think it's better to check `pcmanfm-qt` → `Preferences` → `Display` → `Show icons of hidden files shadowed` by default for the user to distinguish hidden files immediately.

**Comment by stefonarch** [comment] 2021-06-18 11:12
Good point!
