### ISSUE TITLE
Strange graphical glitch with the click-n-drag rectangle on the LXQt desktop

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/pcmanfm-qt#1597] opened 2022-06-03 00:10 UTC
##### Expected Behavior
When you use the click-n-drag rectangle on the LXQt desktop (the thing that lets you select multiple icons at once), it should cleanly draw to the screen, no matter what direction you drag it, and no matter what scale factor is applied to the screen.

##### Current Behavior
If you click-n-drag downwards or to the right, everything works right on all scales. Dragging upwards and to the left works on 1.0x scale. However, when you scale up the display to 1.5x (via LXQt Session Settings "Scale factor" setting), dragging upwards and to the left initially appears to display cleanly, but then it leaves weird trails of lines behind when you drag back down or right. This is hard to explain, so here's a screenshot:

![LXQt 1 1 0 Graphical Glitch](https://user-images.githubusercontent.com/104878738/171759827-d9de95fa-ea1d-45a9-ba23-9abc9d9c4e02.png)

After taking the screenshot, I installed a patched PCManFM-Qt (patched with the code from pull request #1596), rebooted, and retested, and the same behavior is still occurring.

My OS is Lubuntu Kinetic (22.10), with an LXQt 1.1.0 PPA added and installed. I am running everything in a VM made using raw QEMU, with SeaBIOS, 2 CPU cores, 8 GB RAM, 20 GB disk space, and QXL graphics. However, I was also able to reproduce this bug on bare metal with an HP Elitebook 8570p, so this is not unique to the VM.

##### Steps to Reproduce (for bugs)
This is a video showing exactly how to reproduce the bug (after you've got the LXQt 1.1.0 PPA installed). It also shows exactly what the bug looks like. Full instructions on how to reproduce the bug are below the video.

https://user-images.githubusercontent.com/104878738/171759914-fd51b936-6e31-4b2e-a23b-4d9fb7f4c6f7.mp4

1. Open QTerminal, and run the following command sequence:
    `sudo add-apt-repository ppa:ci-train-ppa-service/4856 # This is the LXQt 1.1.0 PPA`
    `sudo apt update`
    `sudo apt full-upgrade`
    `reboot`
2. Click the Application Menu, hover over "Preferences", hover over "LXQt Settings", and click "Session Settings".
3. Increase the scale factor to 1.50, then click "Close". Click "OK" in the window that pops up.
4. Close everything, log out, and log back in (Application Menu, Leave, Logout, Yes, type password, press Enter).
5. Press and hold the left mouse button while the pointer is in the middle of the screen.
6. Start dragging the mouse around in all directions. You'll see the bug surface very obviously and quickly.

##### Context
Glitchy screen = distracting, odd, wrong. (But for the record, you guys have done a great job on this DE!)

##### System Information
* PcManFm-qt version: 1.1.0
* Distribution & Version: Lubuntu 22.10 Kinetic (development release, alpha)
* Qt Version: 5.15.4
* liblxqt Version: 0.17.0-0ubuntu

**Comment by tsujan** [comment] 2022-06-03 00:23
Thanks for the report!

The problem was reported last night and will be fixed by https://github.com/lxqt/pcmanfm-qt/pull/1596 (which fixes a more general issue). See https://github.com/lxqt/pcmanfm-qt/issues/1595#issuecomment-1144402693 and the comments below it.

**Comment by tsimonq2** [comment] 2022-06-03 00:35
While I hoped that would fix it, I cherry picked that patch in a PPA and the problem still seems to exist, not sure if it's the same one?

Let's let @ArrayBolt3 respond with the testing results after that :)

**Comment by tsujan** [comment] 2022-06-03 00:38
@tsimonq2, I'll reopen issues related to pcmanfm-qt if I'm sure they are bugs. Please be patient.

**Closed by tsujan** 2022-06-03 00:38 UTC

**Comment by tsimonq2** [comment] 2022-06-03 00:49
All good, thanks

**Comment by ArrayBolt3** [comment] 2022-06-03 04:07
Bug persists for me with compton, picom, openbox, and KWin-x11. Each one was ran without arguments, and I tried running compton and picom both with openbox, and all by themselves with no window manager running. The same bug occurs no matter what combo of compositor and window manager I use (and also happens with no compositor and no window manager). I had #1596 applied on the system during all these tests. Tests were done on bare metal on an HP Elitebook 8570p.

**Comment by stefonarch** [comment] 2022-06-03 05:16
Somehow it remembers me of https://github.com/lubuntu-team/lubuntu-update-notifier/issues/1 - afaik this was only seen on Lubuntu systems.

**Comment by tsujan** [comment] 2022-06-03 10:06
Not reproducible here with KWin, KWinFT or compiz-reloaded. Also, see https://github.com/lxqt/pcmanfm-qt/issues/1595#issuecomment-1145531090.

That rectangle is called [rubber-band](https://doc.qt.io/qt-5/qrubberband.html). Neither `pcmanfm-qt` nor `libfm-qt` draws it (`libfm-qt` draws the rubber-band only for the detailed list view, which has nothing to do with the desktop); it's drawn by Qt itself.

So, most probably, the bug is outside our code. A workaround might be possible if the sufficient conditions for reproducing it are found — apparently, a scale factor of 1.5 isn't enough.

**Comment by tsujan** [comment] 2022-06-03 10:24
OK, I succeeded in reproducing the issue with a scale factor of 1.7, not only on Desktop but also in other Qt apps that had rubber-band selection rectangles. This video shows the problem in Qt Designer:

https://user-images.githubusercontent.com/981076/171836345-6db8696d-01af-4b3d-a4a8-3089bd7a3613.mp4

The problem is definitely not in LXQt but in Qt itself.

**Comment by ArrayBolt3** [comment] 2022-06-03 21:33
Thank you for your help! I will take this to Qt and see what they think.

**Comment by tsujan** [comment] 2022-06-03 21:58
> I will take this to Qt and see what they think.

A sample file: 
[list_widget.ui.zip](https://github.com/lxqt/pcmanfm-qt/files/8835893/list_widget.ui.zip)

Open it with:
```
QT_SCALE_FACTOR=1.7 designer list_widget.ui
```
Then preview it (with `Ctrl+R`) and draw selection rectangles inside the preview window. To see the glitches, you may need another fractional scale factor instead of 1.7.

**Comment by ArrayBolt3** [comment] 2022-06-03 22:20
Thank you very much! I will attach that to the Qt bug report.

**Comment by tsujan** [comment] 2022-06-03 23:17
@ArrayBolt3 
Thank! If you open a Qt bug report or find an existing one, please add its link to this page.

I'll see if I could find a solution for the detailed list mode. It's the only place where the rectangle is drawn by `libfm-qt`. The code was borrowed from Qt itself; hence inheriting the same problem.

**Comment by ArrayBolt3** [comment] 2022-06-04 00:26
@tsujan Thank you! Here's the Qt bug report: https://bugreports.qt.io/browse/QTBUG-104020

**Comment by tsujan** [comment] 2022-06-04 00:54
Thanks again!

By doing some tests, I found more info:

 1. With Fusion, very thin lines may remain *even without a scale factor*! They're hard to reproduce and hard to see, but I'm sure about their existence. I wasn't able to reproduce them with Breeze or Kvantum.
 2. Because of 1, I think a simple workaround is possible in Qt styles (will try it with Kvantum).
 3. A very simple workaround is possible in the code, by growing the update rectangle by 1 pixel in all directions. However, because of 1, I think the issue is deeper and a real fix is needed.

**Comment by tsujan** [comment] 2022-06-04 03:47
OK, Qt's issue is definitely deeper than this report and isn't limited to selection rectangles. The following video shows a combo popup with a scale factor of 1.7:

https://user-images.githubusercontent.com/981076/171979210-1f4e11f1-6d7b-4420-bbdb-aa46935f1648.mp4

The horizontal line is a glitch.

The problem is in the rectangle that's given to `QWidget::update(const QRect &rect)`. Due to rounding, when the scale factor isn't an integer, the update rectangle can be 1 pixel smaller than the needed rectangle.

Qt doc warns about such issues, but I don't think they're inevitable. Theoretically speaking, when the scale factor isn't an integer, the relevant codes can grow the update rectangle by 1 pixel to avoid such visual glitches.

BTW, the rubber-band problem isn't visible in Dolphin because it updates *the whole view* whenever the selection rectangle changes. That seems like an overkill to me.

**Comment by ArrayBolt3** [comment] 2022-06-06 02:28
Wow, thank you! I'll update the Qt bug report, and maybe see if a fix can be made for for the issue that can be submitted upstream.

**Comment by ArrayBolt3** [comment] 2022-06-06 02:36
I just took a closer look at what you said, and realized that the Qt docs already warn about this. Do you think this should be fixed in Qt by detecting when the scale factor is a non-integer and adjusting accordingly, or would it be better to fix this in LXQt code?

Personally, I think Qt should fix it - this doesn't seem to me like something that would be caught easily, so I'd guess there's probably Qt apps galore that have this problem. If Qt fixes it, everyone's code will work as-is.

**Comment by tsujan** [comment] 2022-06-06 07:38
> or would it be better to fix this in LXQt code?

LXQt doesn't draw the widgets of the above videos; so, it's impossible to fix their problems in LXQt.

**Comment by ArrayBolt3** [comment] 2022-06-08 10:54
Per Eirik Aavitsland on the Qt bug report:

> Qt 5.15 isn't in general prepared to handle fractional UI scaling. Things are better from 6.3.

The Qt bug report was closed as out of scope.
