### ISSUE TITLE
unmounting davs shares close pcmanfm-qt

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#733] opened 2018-07-18 22:40 UTC
running pcmanfm-qt as primary instance from the terminal, mount a davs share - have a look to some files and unmount it via side panel gives the following output:
```
% pcmanfm-qt
isPrimaryInstance
file monitor cannot be created: Vorgang wird vom Backend nicht unterstützt
PlacesView::onEjectButtonClicked
operation finished: 0x0
delete MountOperation

QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
file monitor cannot be created: Der angegebene Ort ist nicht eingehängt
file monitor cannot be created: Vorgang wird vom Backend nicht unterstützt
operation finished: 0x0
delete MountOperation
PlacesView::onEjectButtonClicked
folder unmount
file monitor cannot be created: Keine derartige Schnittstelle »org.gtk.vfs.Mount« des Objekts im Pfad /org/gtk/vfs/mount/1
operation finished: 0x0
delete MountOperation
aboutToQuit
```
I guess i would prefer if pcmanfm-qt don't close :P

**Comment by tsujan** [comment] 2018-07-19 01:04
This may be a duplicate of https://github.com/lxqt/pcmanfm-qt/issues/695 , in which case, https://github.com/lxqt/pcmanfm-qt/pull/725 should be the cure.

**Comment by tsujan** [comment] 2018-07-19 01:12
Oh, there is a 101% chance that it's the same issue: `PlacesView::onEjectButtonClicked...`

**Comment by palinek** [comment] 2018-07-19 05:42
Isn't that a configurable behavior?

**Comment by tsujan** [comment] 2018-07-19 18:26
> the patch apply and compile fine, but don't fix that behaviour

If you mean closing the window on unmounting, it's configurable, as @palinek mentioned. But if you mean the failure in unmounting, it's fixed; isn't it?

**Comment by agaida** [comment] 2018-07-19 19:29
erm - i found that the card should be closed - not pcmanfm at all

**Comment by tsujan** [comment] 2018-07-20 07:24
The current options seem reasonable to me:

(1) Close tab containing removable media.
(2) Change folder in the tab to home folder.

Setting the default to (1) is also reasonable. pcmanfm-qt is closed only if it has one tab and it's unmounted, unless you choose the second option.

However, there was a problem that's fixed in the [PR](https://github.com/lxqt/pcmanfm-qt/pull/725): depending on the machine, the closing might be done before umounting and so, the former might interrupt the latter. The PR waits until unmounting/ejecting is done completely and only then, closes the tab.

**Comment by agaida** [comment] 2018-07-20 17:10
ok

**Closed** 2018-07-21 17:06 UTC
