### ISSUE TITLE
When trying to move an icon on the desktop in RTL mode, it moves to the opposite location on the desktop

### ISSUE THREAD

**Issue by omeritzics** [lxqt/pcmanfm-qt#1494] opened 2021-11-24 16:50 UTC
##### Expected Behavior
Items should move to the location they have been moved.

##### Current Behavior
Items move to the opposite location of the location they have been moved to on the desktop

##### Steps to Reproduce (for bugs)

1. Use a RTL language (Hebrew, Arabic, Persian, etc.)
2. Try to move a desktop icon.

##### System Information

* Distribution & Version: Lubuntu 21.10
* Kernel: 5.13.0-21-generic
* Qt Version: 5.15.2
* LXQt Version: 0.17.1

Video of the bug:

https://user-images.githubusercontent.com/66558205/143282024-8ae88050-e332-42ab-a17c-3154cd7c4ba1.mp4

**Comment by tsujan** [comment] 2021-11-24 17:11
Thanks for reporting!

Although I usually test RTL layout, I didn't do it in the case of desktop. Will look into it.

**Comment by stefonarch** [comment] 2021-11-24 17:39
I can reproduce it with `LANG=he pcmanfm-qt --desktop`

**Comment by tsujan** [comment] 2021-11-24 17:51
Yes. You could also change the layout without changing the language: `pcmanfm-qt --desktop --reverse`

It's very easy to fix; I should only find a needle in the haystack ;)

**Comment by tsujan** [comment] 2021-11-24 20:10
I found the source of the problem. Although `QTListView` uses the RTL coordinates to put items (which is why the layout seems correct), DND reports the position in the usual (LRT) coordinates. I added conditions for RTL to several places and the code worked, but that's not clean.

BTW, trashing on the RTL desktop is also affected (as it should).

Now I'm mistaking my left and right hands for each other; tomorrow, I'll try to find a clean approach with a fresh mind.

**Comment by tsujan** [comment] 2021-11-25 11:18
As was promised: https://github.com/lxqt/pcmanfm-qt/pull/1495

**Comment by tsujan** [comment] 2021-11-25 13:08
Oops! There's also an old bug regarding RTL, which isn't related to DND. The RTL desktop will have a wrong layout if the panel is put at the right side of the screen.

I'll add a commit to the above-mentioned PR for fixing it.

**Comment by tsujan** [comment] 2021-11-25 14:43
Done.

@stefonarch 
It passed my tests but, if you test [the latest PR](https://github.com/lxqt/pcmanfm-qt/pull/1495) (which would be very appreciated), please also do tests with right and left panels.

**Comment by stefonarch** [comment] 2021-11-25 14:56
Just tested shortly, looks working everything. Have only little time for internet next days.

This needs a bugfix release, doesn't it? Funny that it didn't show up earlier.

**Comment by tsujan** [comment] 2021-11-25 15:36
> This needs a bugfix release, doesn't it?

I'd also like a point release for it; the next spring is too late for including a fix for an important bug like this.

I'll test it more and, if no problem surfaced, will make a point release before 2022 (most probably, soon). "Recent Files" will be in it too.

**Closed** 2021-11-26 13:53 UTC
Labels: bug

**Comment by tsujan** [comment] 2021-12-01 11:28
There's a problem with a point release:

libfm-qt has had a backward-incompatible change in a previous commit, so that its ABI version should be changed. Because of that, `lximage-qt`, `lxqt-archiver`, `lxqt-qtplugin` and perhaps other components that need the latter should be recompiled. That will cause a confusion unless we make point releases for them too.

That wouldn't happen if the ccurrent fix was made before https://github.com/lxqt/libfm-qt/commit/6b8d5acd76e7c7eb7707257b006995b17231e72f.

I don't think that a single fix can justify releasing of LXQt 1.1.0, especially when the issue that it fixes had existed for a long time and almost no other component has changed.

@stefonarch, am I wrong here?

**Comment by stefonarch** [comment] 2021-12-01 12:11
I think you're right. 
On the other hand LXQt 1.0.0 will probably be (and stay) the next  LTS version in Lubuntu, which is still the biggest fish in the user pool - for the hebrew and arabic users it's a quite annoying bug. But yes, it hasn't been reported until now.

**Comment by tsujan** [comment] 2021-12-01 12:32
Fortunately, the fix (https://github.com/lxqt/pcmanfm-qt/commit/b201e49ef476c1d1b1183bf271c6eb626b221307) can also be applied by a distro patch to pcmanfm-qt 1.0.0; it doesn't require anything else.

BTW, at least a part of the RTL bug existed since the early versions of pcmanfm-qt but it could be seen only with a right/left panel.

**Comment by stefonarch** [comment] 2021-12-01 13:42
> BTW, at least a part of the RTL bug existed since the early versions of pcmanfm-qt but it could be seen only with a right/left panel.

ok, this explains why , most users don't change much. I had always a right panel for the icon stuff.

**Comment by tsujan** [comment] 2021-12-01 14:44
> I had always a right panel...

I had a left panel for years, even before LXQt. Only a few months ago, I changed my habit.
