### ISSUE TITLE
[Feature request] Make +/- overlay icons hideable

### ISSUE THREAD

**Issue by Zeioth** [lxqt/pcmanfm-qt#1714] opened 2023-01-07 07:02 UTC
**Is your feature request related to a problem? Please describe.**
Add an option to hide the +/- overlay icon on mouseover under edit → preferences → user interface

![screenshot_2023-01-07_08-02-12_982066483](https://user-images.githubusercontent.com/3357792/211136458-247571b9-817c-4fba-8bd7-16950017ea6f.png)

**Comment by stefonarch** [comment] 2023-01-07 07:43
Duplicate of https://github.com/lxqt/pcmanfm-qt/issues/1125
On a personal note I would disable it if there would be an option.

**Comment by tsujan** [comment] 2023-01-07 10:16
→ https://github.com/lxqt/pcmanfm-qt/issues/1712#issuecomment-1374431732

**Closed** 2023-01-07 10:15 UTC
