### ISSUE TITLE
Possible app freeze when mounting encrypted volumes

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/pcmanfm-qt#1414] opened 2021-07-05 05:48 UTC
When plugging my external drive on USB, a dialog is displayed asking for the passphrase. But this one is dead, I get only the frame of the window. I have to kill it. A second after that, I get the whole dialogue which is now working.

##### Expected Behavior
A working dialogue the first time it is displayed.

##### Steps to Reproduce (for bugs)
Plug the drive containing:
```
lsblk /dev/sdc
NAME                                         MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sdc                                            8:32   0 931,5G  0 disk  
├─sdc1                                         8:33   0 734,7G  0 part  
│ └─luks-a070ee60-9570-449a-836b-a0234aa99244
│                                            252:1    0 734,7G  0 crypt /run/media/yves/79fe05bc-6773-44ae-8e28-e9619e16ba85
└─sdc2                                         8:34   0 196,8G  0 part  /run/media/yves/02813F504C55F920
```

##### System Information
* Distribution & Version: Mageia 8 x86_64
* Kernel: 5.10.46-desktop-1.mga8 
* Qt Version: 5.15.2
* libfm-qt Version: 0.16.0
* libqtxdg Version: 3.6.0

This behaviour was already the case in Mageia 7 and LXQt 0.14

**Comment by stefonarch** [comment] 2021-07-05 09:16
So you have 2 partitions on this drive, an emcrypted one and a normal one? I never run into this, but I don't have a similar disk, will prepare one and test.

**Comment by stefonarch** [comment] 2021-07-05 11:10
Tested, confirmed as described, weird window frame to kill.
It happens only when "mount volumes automatically when inserted" is checked in Preferences → Volumes.

**Comment by tsujan** [comment] 2021-07-05 11:31
I can also confirm the freeze in 0.17 when only the first partition is LUKS and auto-mount is enabled. Without auto-mount, there's no freeze.

**Comment by papoteur-mga** [comment] 2021-07-05 11:44
> It happens only when "mount volumes automatically when inserted" is checked in Preferences → Volumes.

I would like to check this setting, but I don't find Preferences / Volumes
Where should it be, or which command should be launched?

**Comment by tsujan** [comment] 2021-07-05 12:35
> I would like to check this setting, but I don't find Preferences / Volumes

`pcmanfm-qt → Edit → Preferences → Volume → Mount removable media automatically...` (for now, uncheck it when a partition table has both LUKS and non-LUKS partitions.

This is similar to https://github.com/lxqt/pcmanfm-qt/pull/1108. The difference is that, now, we have LUKS and non-LUKS partitions in the same drive. I'm not sure how this situation can be worked around...

**Comment by papoteur-mga** [comment] 2021-07-05 13:09
I confirm that this option of automounting is enabled.

**Comment by stefonarch** [comment] 2021-07-05 14:17
Not sure if related, but it was never possible to unmount only one partition on a 2-partition usb drive, always both together will be unmounted.

**Comment by tsujan** [comment] 2021-07-05 14:24
> Not sure if related, but it was never possible to unmount only one partition on a 2-partition usb drive

No, it isn't related to this (I used an external drive).

It may sound strange but we're just lucky that auto-mount works under other circumstances. There's a deep logical flaw in the code, which I'm not sure I can correct — https://github.com/lxqt/pcmanfm-qt/pull/1108 was only a workaround for a special case.

**Comment by tsujan** [comment] 2021-07-05 19:27
A word about how deep the problem is and why I don't expect a fix soon:

The cause of the freeze is that, while a volume of the external drive is being mounted, another volume of the same drive is added and wants to be mounted too because GLib's thread doesn't know when Qt finishes the previous mount.

For ordinary mounts, the process is usually so fast that, when the second volume is added, the mount of the first one is already finished, so that no problem happens (although there's no 100% guarantee). But a LUKS partition needs a password and its mount process lasts as long as the password is entered (because `libfm-qt` works so).

Now, I can add a timer to wait for GLib to add all volumes of an external drive. After that, those volumes can be mounted, *one after the other*. In that way, no freeze will happen.

Should I be happy then? No! Because my laptop has more that one USB port and I can insert a USB stick or external drive into it while the password dialog of the previous external drive is waiting to be filled. If I do so, the app will freeze again, for the same reason, namely, parallel mounts.

**Comment by tsujan** [comment] 2021-07-06 03:24
I just wanted to add that, because of the current structure of [MountOperation](https://github.com/lxqt/libfm-qt/blob/master/src/mountoperation.cpp) in `libfm-qt`, the problem isn't limited to auto-mount. Considering the above-mentioned file, one can imagine other ways of making the app freeze. For example:

 1. Disable all kinds of auto-mount.
 2. Try to mount an encrypted volume by clicking its icon on the side-pane but don't type the password in the prompt dialog.
 3. While the password prompt is there, insert a USB stick (whether encrypted or not) without touching the encrypted volume.

Then the app freezes.

Making `MountOperation` asynchronous may solve the problem (I'm not sure though) but it'll need a structural change and lots of work.

**Comment by tsujan** [comment] 2021-07-07 17:50
After hours of testing various hypotheses, I saw that my previous comments might be misleading. So, I removed them. Instead, this is what I've found (sorry, I can't put it into plain English — technical terms are needed):

 * If an encrypted volume is mounted from `computer:///` (with the latest git `libfm-qt`, that can also be done by right clicking) and another volume is added while the password dialog is shown, everything will be OK. In this case, we use `g_file_mount_mountable()`.
 * If an encrypted volume is mounted from the side-pane and another volume is added while the password dialog is shown, the app will freeze. In this case, we use `g_volume_mount()`.
 * The same freeze happens when a drive with a mixture of encrypted and non-encrypted partitions is auto-mounted because, again, `g_volume_mount()` is used and non-encrypted volumes are added while the password dialog is shown — exactly like the previous case. The existence of the "Lists" side-pane isn't relevant (= the problem is not in it).

The password dialog is shown by using `QDialog::exec()`, which creates a local event loop and waits for the user interaction. The problem happens in that local event loop, which can also be created by other methods — and even without a dialog — but with the same effect (I tested it): `g_file_mount_mountable()` has no problem with it but `g_volume_mount()` will cause a freeze *if another volume is added while that local loop is running.*

We need the above-mentioned local loop (in whatever way it may be created) because we want to type the password in response to `GMountOperation`'s signal "ask-password".

My wild guess is that the problem is in GVFS but I've found no complete workaround so far. I neither know why the same problem doesn't happen with GTK (had a look at `gtk/gtkmountoperation.c` but found nothing useful).

**Comment by tsujan** [comment] 2021-07-08 06:17
Based on the above-mentioned thoughts, I made a workaround here: https://github.com/lxqt/libfm-qt/pull/704

It passed my tests under various circumstances, e.g. with a drive that had 2 ordinary partitions and 2 LUKS partitions with 2 different passwords. But independent tests are needed.

**Comment by stefonarch** [comment] 2021-07-08 17:12
Looks working fine, will make some more tests.

**Comment by tsujan** [comment] 2021-07-08 17:30
> Looks working fine, will make some more tests.

Thanks for testing! And yes, the more tests, the better.

**Closed** 2021-07-21 08:40 UTC
Labels: bug
