### ISSUE TITLE
Cannot copy folder into Virtualbox shared folders

### ISSUE THREAD

**Issue by Kiolali** [lxqt/pcmanfm-qt#1024] opened 2019-10-10 19:24 UTC
##### Expected Behavior

Copy a folder with content into a mounted shared folder (automatically mounted by Virtualbox) should work via file manager if it works on the shell. Therefore file permissions cannot be an issue.

##### Current Behavior

When I paste a folder into the mount I get the error `Error setting permissions`. Only the folder is copied but not the content.

![image](https://user-images.githubusercontent.com/16179562/66599830-6f8a2880-eba4-11e9-830f-ff2165b6a09e.png)

##### Possible Solution

The problem seems to be related to the mountpoint not being owned by the user. When I remount the shared folder with `uid=1000` the problem is gone. However, there doesn't seem to be a practical way to change the `uid` that the shared folder is automatically mounted with (see https://github.com/flokli/virtualbox/blob/d0096b9919f99c4362dd6cf50be2be81307dac33/src/VBox/Additions/common/VBoxService/VBoxServiceAutoMount.cpp#L1485-L1486).

##### Steps to Reproduce (for bugs)

1. Create a shared folder in Virtualbox and enable automatic mounting
2. Start the VM
3. Copy & paste some non-empty folder into the mount

##### Context

```
cpp@cpp-pc:~$ ls -l /media/
insgesamt 8
drwxr-x---+ 2 root root   4096 Okt  9 13:59 cpp
drwxrwx---  1 root vboxsf 4096 Okt 10 21:12 sf_SharedFolderCppVM
cpp@cpp-pc:~$ groups
cpp adm cdrom sudo dip plugdev lpadmin vboxsf sambashare
cpp@cpp-pc:~$ mount | grep SharedFolder
SharedFolderCppVM on /media/sf_SharedFolderCppVM type vboxsf (rw,nodev,relatime,iocharset=utf8,uid=0,gid=127,dmode=0770,fmode=0770,tag=VBoxAutomounter)
```

##### System Information

* Distribution & Version: Lubuntu 19.04
* Kernel: Linux cpp-pc 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 5.12.2+dfsg-4ubuntu1.1
* libfm-qt Version: 0.14.1-0ubuntu2.1
* libqtxdg Version: 3.3.1-0ubuntu2

**Comment by agaida** [comment] 2019-10-10 20:04
Is a virtualbox problem really a LXQt problem? i guess not.

**Comment by tsujan** [comment] 2019-10-10 20:04
By chance, I'd installed Tumbleweed with KDE on VirtualBox 6.0.12 a few days ago: How could Dolphin open the folder in the following screenshot -- let alone copy anything inside it?!

![vbox](https://user-images.githubusercontent.com/981076/66601628-3e662400-ebb5-11e9-9916-ed7927b256e7.png)

I installed pcmanfm-qt plus lxqt-sudo in Tumbleweed, used `lxsudo pcmanfm-qt, and copied a folder into the mount point. All of its contents were copied correctly and accessible from the real computer.

I think you might want to report the problem to VirtualBox..

**Comment by tsujan** [comment] 2019-10-10 20:05
@agaida We have telepathy.

**Comment by agaida** [comment] 2019-10-10 20:06
No, we have not (hmm - maybe) - adding the user to the vboxsf group should solve the problem finally - at least i hope so. So: Nothing to see here, walk along ...

**Comment by tsujan** [comment] 2019-10-10 20:07
> No, we have not

We do ;)

**Comment by agaida** [comment] 2019-10-10 20:07
Ok. Aggreed :D

**Comment by tsujan** [comment] 2019-10-10 20:08
BTW, Tumbleweed's LXQt support seems nice.

**Comment by daniel-k** [comment] 2019-10-10 20:10
I'm not sure if I get your point. The user `cpp` is already in the `vboxsf` group (see context) and manipulating files via shell works like it should. It's also possible to copy first an empty folder via the UI and then the content.

**Comment by agaida** [comment] 2019-10-10 20:12
@tsujan - it rings a bell - problem with remote file systems - maybe it is our problem

**Comment by tsujan** [comment] 2019-10-10 20:18
@agaida I added my user to the vboxsf group and repeated the procedure: all the contents were copied again. So, it's simple: the problem is in @daniel-k's distro. Please close this!

**Comment by tsujan** [comment] 2019-10-10 20:20
And please note that Tumbleweed doesn't even have the latest git pcmanfm-qt in its default repository: I installed 0.14.1. We've fixed all copy problem after 0.14.1 but this one wasn't a problem at all.

**Comment by Kiolali** [comment] 2019-10-10 20:29
I straced what's happening:
```
[pid  1423] mkdir("/home/cpp/Desktop/SharedFolderCppVM/test_folder", 0777 <unfinished ...>
[pid  1423] lstat("/home/cpp/Desktop/SharedFolderCppVM/test_folder", {st_mode=S_IFDIR|0770, st_size=0, ...}) = 0
[pid  1423] chmod("/home/cpp/Desktop/SharedFolderCppVM/test_folder", 040775) = -1 EPERM (Vorgang nicht zulässig)
[pid  1146] stat("/home/cpp/Desktop/SharedFolderCppVM/test_folder", {st_mode=S_IFDIR|0770, st_size=0, ...}) = 0
[pid  1424] lstat("/home/cpp/Desktop/SharedFolderCppVM/test_folder", {st_mode=S_IFDIR|0770, st_size=0, ...}) = 0
[pid  1424] access("/home/cpp/Desktop/SharedFolderCppVM/test_folder", R_OK) = 0
[pid  1424] access("/home/cpp/Desktop/SharedFolderCppVM/test_folder", W_OK) = 0
[pid  1424] access("/home/cpp/Desktop/SharedFolderCppVM/test_folder", X_OK) = 0
[pid  1424] stat("/home/cpp/Desktop/SharedFolderCppVM/test_folder/.directory", 0x7f8351c1aac0) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)```

Maybe it's throwing the error when `chmod` is failing? 

@tsujan Do you have a hint what to look for? I understand that this is maybe not your fault, but I don't see where the problem may be rooted otherwise.

**Comment by tsujan** [comment] 2019-10-10 20:35
@Kiolali If I *see* a problem, I'll fix it. I did as you described (and *thanks for your good bug report!*) but didn't encounter a problem under Tumbleweed, which uses 0.14.1.

We've fixed so many issues after 0.14.1, so that I really don't remember if the copy problem was one of them. However, I clearly remember that I fixed copy problems in a few patches months ago.

**Comment by tsujan** [comment] 2019-10-10 20:48
@Kiolali This patch is made after 0.14.1 and isn't specific to SMB: https://github.com/lxqt/libfm-qt/commit/2fc359a71627ff19fd06654fd6de568f63225c58

But I don't think it's related to your problem because I downloaded Tumbleweed's `libfm-qt-0.14.1-1.8.src.rpm` and saw that it contained no patches.

**Comment by agaida** [comment] 2019-10-10 21:00
dumb question - how do i set up shared folders :D

**Closed by agaida** 2019-10-10 21:00 UTC

**Comment by Kiolali** [comment] 2019-10-10 21:08
@tsujan Thank you for looking into this!

I just tried to reproduce the same behaviour with a Samba mount and it indeed is the same. Here's what the mount point looks like (I intentionally mounted it like the VirtualBoxAutoMounter would mount the shared folder concerning permission masks and uid/gid):
```
cpp@cpp-pc:~$ mount
//192.168.178.100/tmp on /mnt type cifs (rw,relatime,vers=3.1.1,cache=strict,username=root,uid=0,forceuid,gid=127,forcegid,addr=192.168.178.100,file_mode=0770,dir_mode=0770,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1)
cpp@cpp-pc:~$ ls -l /
drwxrwx---   2 root vboxsf     0 Okt 10 23:01 mnt
```
It's important to note that the directory mask has to be set to `0770`, otherwise this doesn't occur. The patch you've pointed at looks like it might work around this. I guess that it will then behave similar to plain `cp`, not trying to change permissions on the newly created folder.

**Comment by agaida** [comment] 2019-10-10 21:19
ok - if samba has a problem - just update your ubuntu - or switch to a distribution that does take care of users. To be honest, i don't know the ubuntu packages - and i don't care. It has historical reasons, i know that these changes are in debian and that i asked for the permission to fix these bugs for the upcoming stable release because we was in deep freeze. And in case such things happen there are two ways to handle these bugs: Just ignorem them or fix them - it seems the Lubuntu Team has chosen the first option.

**Comment by tsujan** [comment] 2019-10-10 22:00
@agaida Late answer to your question: You could choose a shared folder inside the real hard and a mount point for the guest by using Virtual machine settings → Shared folder. Frankly, it was the first time I did so -- I usually use DND, which is easier.

BTW, IMHO, if there is still a mount problem, it can't be so serious.

**Comment by tsujan** [comment] 2019-10-10 22:05
@Kiolali That kind of problem -- like the one with SMB -- is definitely fixed. Moreover, the folder is automatically refreshed on deleting/creating/renaming files.

**Comment by agaida** [comment] 2019-10-11 00:45
@tsujan - ok, i'm sometimes an idiot - vbox-guest-dkms should be installed i guess - for some unknown reasons it isn't on the iso - maybe i should have a look into our build system :)

**Comment by tsujan** [comment] 2019-10-11 03:37
With some distros, `VBoxGuestAdditions.iso` should be used after installation (the most complete method); with some others, some packages from their repositories should be installed; still with others, nothing needs to be done.

**Comment by agaida** [comment] 2019-10-11 15:17
Sad, so sad :D - the kernel part works fine, for vboxfs one need the complete vbox-guest-foo - and with kernel 5.2 or 5.3 on need to patch this crap or use the not released guest additions 6.0.13 :D - easy, isn't it?

**Comment by tsujan** [comment] 2019-10-11 15:32
Months ago, I installed vbox additions on your Debian LXQt ISO -- wanted to compile some things there. It was so easy but I don't remember what I did ;) On Tumbleweed, it was a piece of cake: installed it from `VBoxGuestAdditions.iso` after doing `sudo zypper in kernel-devel gcc make`

**Comment by agaida** [comment] 2019-10-11 16:05
it is easy if one use old kernels
