### ISSUE TITLE
Weird slowdown after update to 2.0 (themeing related)

### ISSUE THREAD

**Issue by Rabcor** [lxqt/pcmanfm-qt#1903] opened 2024-05-07 11:21 UTC
##### Expected Behavior

Opens and runs at normal speed.
##### Current Behavior

Takes a long time to launch and has many odd slowdowns.

https://github.com/lxqt/pcmanfm-qt/assets/5684325/6403b7e6-5638-488a-b9d1-dd054e1b5d72

The slowdowns you see after the window opens frequently occur during regular use.

The issue is slightly worse on wayland(wlroots compositors) than on X. The issue is bad enough that when a theme is applied this way, pcmanfm-qt is more or less unusable (it can be used, the experience is just exceptionally bad).

##### Steps to Reproduce (for bugs)

Using GTK themeing: `QT_QPA_PLATFORMTHEME=gtk3 pcmanfm-qt` or `XDG_CURRENT_DESKTOP=gnome pcmanfm-qt`

Using Kvantum/qt6ct themeing:
1. Set a theme using kvantum (I'm using [sweet kde](https://store.kde.org/p/1294013/), but the theme itself doesn't seem to matter)
2. Configure qt5ct/qt6ct to use the kvantum theme.
3. run pcmanfm-qt with qt5ct or qt6ct themeing enabled: `QT_QPA_PLATFORMTHEME=qt6ct  pcmanfm-qt`

Note: I don't think the kvantum theme is necessary at all to reproduce the issue with qt5ct and qt6ct.
##### System Information

* PcManFm-qt version: 2.0.0
* Distribution & Version: endeavouros 6.6.30-1-lts
* Qt Version: 6.7.0
* liblxqt Version: None

##### Workarounds:
Unst QT_QPA_PLATFORMTHEME and use QT_STYLE_OVERRIDE instead.
`QT_QPA_PLATFORMTHEME= QT_STYLE_OVERRIDE=kvantum pcmanfm-qt`

Downside is pcmanfm-qt will not have an icon theme active. Not sure how that can be fixed beyond setting `XDG_CURRENT_DESKTOP` variable to some installed DE (which can end up causing the same issue again).

**Comment by tsujan** [comment] 2024-05-07 13:31
Your problem seems to be related to qt6ct, the gtk3 style plugin, or how you set EVs. It isn't reproducible with pcmanfm-qt and LXQt plugin (`QT_QPA_PLATFORMTHEME` = lxqt, or better, `XDG_CURRENT_DESKTOP` = LXQt) when Fusion, Kvantum or Breeze is used as the style, whether under X11, LabWC, Wayfire or kwin_wayland.

Closing because this isn't about pcmanfm-qt, but you could add more info if needed. You could also use [Discussions](https://github.com/lxqt/lxqt/discussions).

**Closed by tsujan** 2024-05-07 13:31 UTC

**Comment by Rabcor** [comment] 2024-05-07 18:11
> Your problem seems to be related to qt6ct, the gtk3 style plugin, or how you set EVs. It isn't reproducible with pcmanfm-qt and LXQt plugin (`QT_QPA_PLATFORMTHEME` = lxqt, or better, `XDG_CURRENT_DESKTOP` = LXQt) when Fusion, Kvantum or Breeze is used as the style, whether under X11, LabWC, Wayfire or kwin_wayland.
> 
> Closing because this isn't about pcmanfm-qt, but you could add more info if needed. You could also use [Discussions](https://github.com/lxqt/lxqt/discussions).

I tested it under 3 environments, sway, i3 and hyprland.

I do not have lxqt installed I am only using pcmanfm-qt, and this is clearly a problem with pcmanfm-qt considering it happens **only** in pcmanfm-qt and **only** since pcmanfm-qt 2.0 update...

Of course it doesn't happen when i use` QT_QPA_PLATFORMTHEME=lxqt XDG_CURRENT_DESKTOP=LXQt` because it might as well be unsetting those variables considering lxqt is not installed.

So what you mean to say is pcmanfm-qt is a part of lxqt and does not need to work without lxqt and only bugs that occur on lxqt are actual bugs?

https://github.com/lxqt/pcmanfm-qt/assets/5684325/a60268cf-c10c-4e5a-bedd-89d0958a45f2

This is not what i would call a fix, yeah it launches ok, but no themeing is applied.

**Comment by tsujan** [comment] 2024-05-07 18:55
> I do not have lxqt installed

It's not about LXQt but any reliable Qt plugin system with correct EVs set, whatever they may be.

> granted pcmanfm-qt seemed to just be using it's own theme...

pcmanfm-qt has never had a hard-coded theme.

> even installing liblxqt doesn't make either of these variables do anything for me.

liblxqt has nothing to do with Qt plugins; lxqt-qtplugin and libqtxdg do.

**Comment by Rabcor** [comment] 2024-05-07 19:01
> It's not about LXQt but any reliable Qt plugin system with correct EVs set, whatever they may be.
If these are not the correct EVs, then what EVs are? on hyprland, sway and i3 you gotta set these EVs by hand, so I'd love to know if i'm missing something important... Have you tried on one of these? Or for that matter tried on any of the environments you tested using the actual variables i specified in the isseu and not the lxqt ones?

But I don't seem to be, pcmanfm-qt loads the theme, it jsut takes a very long time.

> pcmanfm-qt has never had a hard-coded theme.
It was using some theme, and ignoring the qt6ct settings... I could have been wrong about this though, in which case the issue only started happening in 2.0 and wasn't present in the version before (I can't check because i lost that package)

> liblxqt has nothing to do with Qt plugins; lxqt-qtplugin and libqtxdg do.
are you saying i should install them? should they be a dependency of pcmanfm-qt?

Because I can... But i thought pcmanfm-qt was supposed to be able to work without thinking it was on lxqt.

**Comment by stefonarch** [comment] 2024-05-07 19:18
I've just tested a fresh user with  default labwc setting, just added `QT_QPA_PLATFORMTHEME=qt6ct` to  labwc's environment file. 

Configured qt6ct with kvantum theme and a bigger font and can't notice any misbehaviour/slowdown. Can you reproduce it with a fresh user?

**Comment by Bluey26** [comment] 2024-05-07 19:25
I just have tried those command lines in the reproduce steps, and i do not notice any slowdowns: It was tested in i3 and in sway.

`QT_QPA_PLATFORMTHEME=gtk3 pcmanfm-qt ` or `XDG_CURRENT_DESKTOP=gnome pcmanfm-qt` seems to take the same to load as `pcmanfm-qt` in both WMs

**Comment by Rabcor** [comment] 2024-05-07 19:33
> I've just tested a fresh user with default labwc setting, just added `QT_QPA_PLATFORMTHEME=qt6ct` to labwc's environment file.
> 
> Configured qt6ct with kvantum-dark widget and a bigger font and can't notice any misbehaviour/slowdown. Can you reproduce it with a fresh user?

Interesting, i tried on a fresh user, it doesn't happen there. But on my main user it happens on all those 3 environments i tested :thinking:

**Comment by Rabcor** [comment] 2024-05-07 20:37
Ok, after quite a bit of digging, i managed to figure out how to replicate the issue on a new user.

It happens when i have a specific icon theme enabled.

When I try to use the tokyo nights icons (both light and dark, didn't try the other 2) available here: https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/tree/master/icons

That's when the issue happens, if I set a different icon theme, the issue doesn't occur at all, very strange.
