### ISSUE TITLE
Displayed fields and field width should be configurable in list view

### ISSUE THREAD

**Issue by ryanmusante** [lxqt/pcmanfm-qt#787] opened 2018-09-30 01:43 UTC
##### Current Behavior
Owner and group fields isn't needed in my configuration, request setting to disable

##### Possible Solution
Option to remove in advanced settings

##### Context
Columns smaller, less information to display for more relevant colums

##### System Information

- Manjaro x86_64 17.1.12 
- 4.18.11-25-tkg-pds
- qt5ct 0.36-1
- lxqt-build-tools-git 0.3.2-1 
- libqtxdg-git 3.2.0.11.g374f418-2 
- libfm-qt-git 0.13.1.225.gd37f4ad-1 
- pcmanfm-qt-git 0.13.0.191.g150d8fb-2

**Comment by agaida** [comment] 2018-09-30 02:01
I would go a step further - we should add some more fields but display only a set of relevant fields by default. Also important: The width of the fields should be configurable and saved on leave.

**Comment by tsujan** [comment] 2018-09-30 02:05
OK, agreed with all.

**Comment by tsujan** [comment] 2018-09-30 19:07
I was looking into how columns could be made hidden but encountered a bug in the detailed list. It should be fixed first.

I never use the detailed list; so, it could be improved only by users' reports.

**Comment by tsujan** [comment] 2018-11-06 20:11
Duplicate of https://github.com/lxqt/pcmanfm-qt/issues/622

**Closed by tsujan** 2018-11-06 20:11 UTC
Labels: enhancement
