### ISSUE TITLE
SSH bookmarks may fail if dir is automatically changed to home on unmounting

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1103] opened 2020-04-26 18:36 UTC
EDITED
##### Expected Behavior

Access by bookmarks for a previously unmounted  ftp folder should work.
##### Current Behavior

Clicking the bookmark or pasting the address in the bar does nothing when "switch to home folder" is set on unmounting folder in Preferences > volumes

##### Steps to Reproduce (for bugs)

1. Bookmark and access an ftp or ssh in pcmanfm-qt, set to "switch in to home folder" in preferences > volumes, when unmounting.
2. Unmount it
3. Click the bookmark, opens a blank tab with title and address
4. Press F5 (or restart pcmanfm-qt completely) and it opens.

##### System Information

* Distribution & Version: arch and git checkout
*

**Comment by tsujan** [comment] 2020-04-26 19:20
Not reproducible. I click on bookmark and SFTP is mounted after I unmount it. I checked SMB too: the same result.

Are you sure you've upgraded your LXQt installation to 0.15.0 correctly? I ask because this is the second unreproducible report.

Or maybe an extra piece of information is missing? Closing until you find it if that's the case...

**Comment by stefonarch** [comment] 2020-04-27 12:15
I'll test a clean user with default configs when I have spare time, only thing I can guess are some configurations. Would be nice if somebody else could check those stuff  too.

**Comment by tsujan** [comment] 2020-04-27 14:58
If there is a bug, I'll be happy to be able to reproduce it because, only in that way, I could fix it.

Are you sure that you don't mistake a probable delay for the lack of folder loading? At the moment of clicking the bookmark, check whether the cursor is busy inside pcmanfm-qt's view.

**Comment by stefonarch** [comment] 2020-04-27 17:47
I tested enough, no delay, cursor=arrow, it's just blank and not even the right click menu appears. 
Just reload button or f5  fixes. Only tab title and path are displayed.

**Comment by tsujan** [comment] 2020-04-27 18:03
Very strange!

Logically, there should be a difference we still don't about — otherwise, I would see it at least once.

**Comment by stefonarch** [comment] 2020-04-27 18:25
Ok, found it, on a clean user it works fine, but when "switch to home folder" is selected  instead of "close tab" in pcmanfm's preferences it behaves like described. 
Will update the first posting.

**Comment by tsujan** [comment] 2020-04-27 18:28
OK, I'll test that soon. Thanks for taking time and doing tests!

**Comment by tsujan** [comment] 2020-04-27 18:36
Yes, with that option, I can reproduce the issue. Will change the title.

**Comment by tsujan** [comment] 2020-04-27 19:35
The fix is here https://github.com/lxqt/pcmanfm-qt/pull/1105. Please test!

It was an old bug. I should make a point release for pcmanfm-qt but will wait a little to see if another bug surfaces.

**Closed** 2020-04-27 19:45 UTC
Labels: bug
