### ISSUE TITLE
Mounting a CIFS share hangs entire lxqt

### ISSUE THREAD

**Issue by fenugrec** [lxqt/pcmanfm-qt#847] opened 2018-12-21 03:15 UTC
##### Expected Behavior
Either of these would be acceptable:
- properly mount CIFS shares, by prompting required password
- abort a CIFS mount operation in case of issues (password or network)

##### Current Behavior
when attempting to mount one such device from within pcmanfm-qt, it hangs and all running lxqt processes, hang forever 

##### Possible Solution
- hard timeout on mount operations - if it doesn't complete due to a missing password (like above) or network issues), abort it ?
- magically detect that the mount backend is prompting for a password ?
- magically detect "problematic" mount points and refuse / warn before mounting ?

##### Steps to Reproduce (for bugs)
1. Needs any kind of CIFS share in /etc/fstab that looks like this and requires a password:
`//192.168.1.100/shn	/mnt/shn	cifs	noauto,ro,user=guest,gid=100,users	0 0`
1. In pcmanfm-qt, Right click on the device -> Mount
1. entire lxqt enviroment is unusable. I wasn't able to completely recover from this without rebooting

##### System Information
* Distribution & Version: Artix x86-64
* Kernel: 4.16.84
* Qt Version: 5.11.2
* lxqt-build-tools Version: N/A
* libqtxdg Version: 3.2.0 c0620e4
* libfm-qt Version: 0.13.1 ec51711
* Package version:  0.13.0  f254a92

**Comment by tsujan** [comment] 2018-12-21 03:50
Closed because:

 1. The issue template is ignored.
 2. Here, we don't develop `pcmanfm`.

**Comment by fenugrec** [comment] 2018-12-21 04:14
I am actually using pcmanfm-qt. Updated the issue, sorry.

**Comment by fenugrec** [comment] 2018-12-23 01:55
Thanks. I've just tried pcmanfm-qt from git (0.13.0.244.gf254a92-1), and I thought it solved this but there's still some problems.

First attempt to right-click + "Mount" just gave me an error (which is fine, system at least stays usable).
Second attempt, I just right-clicked another unmounted share, and got the same initial problem (pcmanfm-qt hangs, entire lxqt system is unusable).

**Comment by tsujan** [comment] 2018-12-23 02:39
> ... but the other lxqt processes are unresponsive.

pcmanfm-qt can't affect other LXQt processes. The problem may be somewhere else.

What about unchecking "Desktop" in `LXQt Session Settings`, rebooting and doing the same thing with another file manager like Dolphin?

**Comment by fenugrec** [comment] 2018-12-23 03:30
> unchecking "Desktop" in LXQt Session Settings

Just tried, and now the behavior is stable : attempting to mount from within pcmanfm gives me an error box

```
Password for guest@//192.168.1.100/shn: mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
but continues to work fine.

I will try Dolphin later and update here.

**Comment by tsujan** [comment] 2018-12-23 18:58
> [EDIT] Tried dolphin, similar issue : cannot mount shares, program is unresponsive unless I attach with gdb and pass the SIGTTOU signals manually.

If Dolphin shows the same symptom, the issue is somewhere else -- it can't be in pcmanfm-qt (Dolphin uses KIO, while pcmanfm-qt uses GIO).

**Comment by tsujan** [comment] 2018-12-23 19:08
Do you have the Removable Media plugin on the panel? If so, you could retry after removing it.

**Comment by fenugrec** [comment] 2018-12-23 21:34
> Removable Media plugin on the panel
I don't know what you mean, is that something inside pcmanfm-qt ?

**Comment by tsujan** [comment] 2018-12-23 22:10
> is that something inside pcmanfm-qt ?

No, of course! Since you said the hang happened with Dolphin too, I concluded that the problem is not in pcmanfm-qt.

**Comment by tsujan** [comment] 2018-12-23 22:39
Maybe, some other app that deals with mount. Otherwise, why should the same thing happen with Dolphin?

**Comment by fenugrec** [comment] 2018-12-23 22:46
I've just re-tested right now after a full system update and Dolphin is  "working" (i.e. not freezing). Just to summarize :
- Dolphin : cannot mount, but doesn't hang
- pcmanfm-qt without "desktop" : cannot mount, doesn't hang
- pcmanfm-qt with "desktop" : cannot mount, hangs

**Comment by tsujan** [comment] 2018-12-30 11:17
> pcmanfm-qt without "desktop" : cannot mount, doesn't hang
> pcmanfm-qt with "desktop" : cannot mount, hangs

pcmanfm-qt with Desktop only shows the desktop folder as Desktop and can't affect mounts.

**Comment by tsujan** [comment] 2020-05-19 07:39
Most probably, this was related to https://github.com/lxqt/pcmanfm-qt/issues/1106 and fixed in https://github.com/lxqt/pcmanfm-qt/commit/d513cf42f55803c5eabd6bccfc7aa17f336b8a58

Please upgrade to 0.15.1.

**Closed by tsujan** 2020-05-19 07:39 UTC
