### ISSUE TITLE
Tabs are not remembered after rebooting the computer

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1884] opened 2024-03-25 14:28 UTC
**Steps to reproduce**
open PCManFM-Qt
open eleven tabs; the first three tabs are different folders that are located on  an external device
close the PCManFM-Qt
restart PCManFM-Qt
let the first three tabs open and close all other tabs
close the PCManFM-Qt
reboot the computer
open PCManFM-Qt

**Result**
the third tab is not there any more; instead of two tabs, there are 11 tabs

**Expectation**
there should be only three tabs

**Remark**
this behavior didn't happen to me only one time, but always after rebooting the computer

**System**
Lubuntu 23.10
PCManFM-Qt 1.3.0

if this issue does not exist in PCManFM-Qt 1.4.1, then I'm sorry for this report

**Comment by tsujan** [comment] 2024-03-25 15:36
Not reproducible, and duplicate of https://github.com/lxqt/pcmanfm-qt/issues/1873

**Closed** 2024-03-25 15:35 UTC

**Comment by ralf3u** [comment] 2024-08-04 06:24
@tsujan You wrote on March 25:
>Not reproducible, [...]

On March 25 was the the latest release 1.4.1. Now I use the version 1.4.1, in Lubuntu 24.04. After rebooting the computer the order of the open tabs are not remembered.

Could you please reopen the issue?

**Comment by stefonarch** [comment] 2024-08-04 06:38
I don't use much tabs, but I tested too now. Opening several different tabs, restarted the "Desktop" module in session settings: tabs are reopened in the same order.

**Comment by ralf3u** [comment] 2024-08-04 07:42
This is what I did:
1. 11 tabs are open
2. with the mouse: grab the 6th tab and drop it completely on the right side
3. reboot the computer

**Comment by ralf3u** [comment] 2024-08-04 18:08
Could someone please reopen the issue?
Or should I open a new issue?

**Comment by tsujan** [comment] 2024-08-04 18:15
> Could someone please reopen the issue?

An issue that cannot be reproduced will not be reopened.

> Or should I open a new issue?

Please don't make duplicate reports.

**Comment by ralf3u** [comment] 2024-08-04 21:20
So, the issue is only on my computer. Maybe the the issue appears because I didn't make a fresh installation but an upgrade of Lubuntu. How can I reset all the settings of PCManFM-Qt 1.4.1 to retry the issue?
Thank you for an answer in advance.

**Comment by ralf3u** [comment] 2024-08-04 21:34
Should I delete all documents of .config/pcmanfm-qt/lxqt?

**Comment by tsujan** [comment] 2024-08-04 22:54
I don't think your problem is in the settings, but yes, if you want to start with fresh settings, first stop pcmanfm-qt from LXQt Session Settings and then rename that folder (instead of deleting it). However, I'm not sure if Lubuntu hasn't changed the default settings.

Please use https://github.com/lxqt/lxqt/discussions for questions.

**Comment by ralf3u** [comment] 2024-08-05 06:46
This is what I did:
1. I closed the window  pcmanfm-qt.
2. I opened the file-manager dolphin.
3. In .config/pcmanfm-qt/lxqt I changed the document name from settings.conf to settings_2.conf.
4. I rebooted the computer.

Now the tabs are remembered after rebooting the computer.

Thank you so much for your help.

**Comment by ralf3u** [comment] 2024-08-06 05:56
Issue is still there. This is what I did: Two different tabs are open in pcmanfm-qt. After rebooting the computer there is only one tab, although the checkbox "Reopen last window tabs in a new window" is activated.

**Comment by ralf3u** [comment] 2024-08-06 06:00
The issue is still there maybe because of this last entry in settings.conf:
`TabPaths=@Invalid()`

**Comment by tsujan** [comment] 2024-08-06 08:57
@ralf3u 
Unless you give us a way of reproducing it, we can do nothing. None of your descriptions has been reproducible so far.

You don't nee to reboot. It's enough to stop Desktop from LXQt Session Settings and start it again. If the problem doesn't happen in that way and only happens when you reboot, then maybe there's a problem in your LXQt session which doesn't make pcmanfm-qt quit gracefully.

**Comment by ralf3u** [comment] 2024-08-06 09:07
>It's enough to stop Desktop from LXQt Session Settings and start it again.

Sorry to ask, but I don't know what you mean. Do you mean that I should logout and login again?

**Comment by tsujan** [comment] 2024-08-06 09:16
> I don't know what you mean

I don't know which part of my comment you didn't understand. Don't you have LXQt Session Setting? If you do, it shows that Desktop is running. You could choose it and click "Stop" and after a few seconds "Start" to restart it.

**Comment by ralf3u** [comment] 2024-08-06 10:42
>Don't you have LXQt Session Settings?

I can find LXQt Session Settings in main menu, then Preferences, then LXQt Settings, and then Session Settings.

>If you do, it shows that Desktop is running. You could choose it and click "Stop" and after a few seconds "Start" to restart it.

I can't find a hint that Desktop is running, and I can't find "Stop" or Start".

**Comment by stefonarch** [comment] 2024-08-06 13:26
> I can't find a hint that Desktop is running, and I can't find "Stop" or Start".

Open it, there are "Modules" and a list, below is a Start and a Stop button. Select "Desktop" (Schreibtisch in german).

**Comment by ralf3u** [comment] 2024-08-06 15:42
>Open it, there are "Modules" and a list, below is a Start and a Stop button. Select "Desktop" [...]

Thank you for your help. Indeed it is in the left point "Basic Settings".

**Comment by ralf3u** [comment] 2024-08-06 15:49
I solved the issue by adding the full path of the tabs as value in `TabPaths=` in the document `settings.conf` that is located in `.config/pcmanfm-qt/lxqt`. Between the full paths, I added one comma and one space. Example:
`TabPaths=/home/fgg, /home/fgg/Documents`
Then I saved the document.

**Comment by tsujan** [comment] 2024-08-06 18:48
> I solved the issue by adding the full path of....

That key isn't for manual editing; it'll be overwritten as soon as pcmanfm-qt quits. Your problem (if any) is somewhere else.

**Comment by ralf3u** [comment] 2024-08-06 21:09
>it'll be overwritten as soon as pcmanfm-qt quits

But it works for me.

The strange thing is that there are now a lot of documents in .config/pcmanfm-qt/lxqt:
```
recent-files.conf
settings.conf
settings.conf.lock
settings.conf.lock.rmlock
settings.conf.lock.rmlock.rmlock
```

In the document recent-files.conf there is this code:
```
[Recent]
Files=@Invalid()
```

**Comment by tsujan** [comment] 2024-08-07 08:45
> The strange thing is that there are now a lot of documents in .config/pcmanfm-qt/lxqt:

Those lock files seem very suspicious to me.

**Comment by ralf3u** [comment] 2024-08-07 15:21
>Those lock files seem very suspicious to me.

For me too. Today there is only one lock file. I think that I deleted them yesterday. Some days ago I saw around 7 lock files.

**Comment by ralf3u** [comment] 2024-08-08 09:18
Now the issue was fixed. I don't know why. Maybe it is because of the update – but I do an update normally every day. Now I don't need to paste full paths in `TabPaths=` manually any more. It is done automatically. And the lock files disappeared.

**Comment by ralf3u** [comment] 2024-09-20 13:15
The issue is still there. So, this is the alternative that I use and that works for me: https://github.com/lxqt/pcmanfm-qt/issues/1884#issuecomment-2271613846.

**Comment by ralf3u** [comment] 2024-10-18 11:38
**Just for documentation**
Compared to Lubuntu 24.04, Lubuntu 24.10 is even worse because https://github.com/lxqt/pcmanfm-qt/issues/1884#issuecomment-2271613846 has no influence.

**Possible solution for the future**
Next time on a new installation of a computer system, this is what I intend to do before upgrading the computer system:
- close all tabs of PCManFM-Qt and 
- eject the SD-card.

Maybe then the issue will not occur any more.

**Comment by ralf3u** [comment] 2024-10-18 12:37
The current title of this issue is:
`Tabs are not remembered after rebooting the computer`
I recognized that this is not true. The correct title should be:
`Tabs from an external device are not remembered after rebooting the computer`
If all open tabs are located on the SSD, then all open tabs are remembered by PCManFM-Qt after rebooting the computer.
PCManFM-Qt remembers all open tabs from a SD-card when closing restarting PCManFM-Qt.

Maybe this could help to fix the issue:
After a computer restart if I press the shortcut to let appear the file-manager, a dialog-box appears with this text before PCManFM-Qt is shown:
```
! Error when getting information for file "/media/...": No such file or directory
OK
```
Instead of "/media/..." there is the full path.
But the full path exists in PCManFM-Qt.
And right after the login the system recognized the SD-card.

With the editor Geany there is the same problem after upgrading to Lubuntu 24.10. After rebooting the computer Geany does remember all open tabs from the SSD, but Geany does not remember the open tabs of documents that are located on the SD-card. Geany remembers all open tabs from a SD-card when closing restarting Geany.

I'm sure that the issue exists because before to upgrade I didn't eject the SD-card.

**Comment by tsujan** [comment] 2024-10-18 17:02
A directory path to a media that isn't mounted (yet) doesn't exist. No tab can be restored for a nonexistent directory; hence the error message. This is the normal behavior.

> And right after the login the system recognized the SD-card.

Recognizing is not mounting.

**Comment by ralf3u** [comment] 2024-10-19 22:22
>Recognizing is not mounting.

With recognizing I meant mounting.

**Comment by ralf3u** [comment] 2024-11-02 20:00
>With recognizing I meant mounting.

I was wrong. After rebooting the computer, the SD-card is mounted in the panel because I can see the eject-symbol in "Removable Media" on the right side of the SD-card.

If I open PCManFM-Qt, there is on the left side the SD-card, but it is not mounted because there is no eject-symbol on the right side although the SD-card is mounted according to the panel. In the moment where I click on the SD-card within PCManFM-Qt, then an eject-symbol does appear and then the SD-card is mounted.

In Preferences, in Volume, "Mount mountable volumes automatically on program startup" is activated.

How can I make it, that PCManFM-Qt mount automatically the SD-card after a computer restart? Why the SD-card is mounted according to the panel, but not mounted according to PCManFM-Qt?

Thank you in advance for an answer.
