### ISSUE TITLE
Move here wont work for german user

### ISSUE THREAD

**Issue by kellerleicheorig** [lxqt/pcmanfm-qt#435] opened 2016-12-22 18:20 UTC
Move here for German user doesn't work. The file wont move in a new folder. Copy here works...

**Comment by agaida** [comment] 2016-12-22 18:23
Geht das nich irgenwie noch knapper? So etwa: "Geht nich!1!!"

**Comment by kellerleicheorig** [comment] 2016-12-22 18:29
Bestimmt geht es knapper, leider bekomme ich keine Terminalausgabe, sonst hätte ich die Angegeben, Aber weisst de was lass es bleiben, ich kann drauf verzichten... Frohes Fest

**Comment by tsujan** [comment] 2016-12-22 18:41
Bitte auf Englisch!

@kellerleicheorig 
Do you mean drag-and-drop? Here, it works well with `LANGUAGE=de pcmanfm-qt`.

**Comment by kellerleicheorig** [comment] 2016-12-22 19:12
Maybe a video tells more as thousand words
https://youtu.be/3sA_rRVCXd8
Hopeful now my issues will be understand...

**Comment by tsujan** [comment] 2016-12-22 19:18
I'd understood your problem (Ich hatte Ihr Problem verstanden) but I can't reproduce it with `LANGUAGE=de pcmanfm-qt`. @agaida, can you?

**Comment by kellerleicheorig** [comment] 2016-12-22 19:44
Okay renamed now my hidden folder pcmanfm-qt, and the hidden folder pcmanfm, rebooted my system, and now it's works. So it is a setting problem, but don't know which...

Attach my settings file
[Behavior]
AutoSelectionDelay=600
BookmarkOpenMethod=current_tab
ConfirmDelete=true
ConfirmTrash=false
NoUsbTrash=false
QuickExec=false
SingleClick=true
UseTrash=true

[Desktop]
BgColor=#000000
DesktopCellMargins=@Size(3 1)
DesktopIconSize=48
FgColor=#ffffff
Font="Sans Serif,10,-1,5,50,0,0,0,0,0"
ShadowColor=#000000
ShowHidden=false
ShowWmMenu=false
SortColumn=name
SortFolderFirst=true
SortOrder=ascending
Wallpaper=/home/daniel/Bilder/Wallpaper/Christmas/pcloshollyballs.jpg
WallpaperMode=stretch

[FolderView]
BackupAsHidden=false
BigIconSize=48
FolderViewCellMargins=@Size(3 3)
Mode=icon
ShadowHidden=false
ShowFilter=false
ShowFullNames=false
ShowHidden=false
SidePaneIconSize=24
SmallIconSize=24
SortCaseSensitive=false
SortColumn=name
SortFolderFirst=true
SortOrder=ascending
ThumbnailIconSize=128

[Places]
PlacesApplications=true
PlacesComputer=true
PlacesDesktop=true
PlacesHome=true
PlacesNetwork=true
PlacesRoot=true
PlacesTrash=true

[System]
Archiver=file-roller
FallbackIconThemeName=elementary
OemplateTypeOnce=false
OnlyUserTemplates=false
SIUnit=false
SuCommand=gksu %s
TemplateRunApp=false
TemplateTypeOnce=false
Terminal=qterminal

[Thumbnail]
MaxThumbnailFileSize=4096
ShowThumbnails=true
ThumbnailLocalFilesOnly=true

[Volume]
AutoRun=true
CloseOnUnmount=true
MountOnStartup=true
MountRemovable=true

[Window]
AlwaysShowTabs=false
FixedHeight=480
FixedWidth=640
FullWidthTabBar=true
LastWindowHeight=816
LastWindowMaximized=false
LastWindowWidth=1507
PathBarButtons=true
RememberWindowSize=true
ShowMenuBar=true
ShowTabClose=true
SidePaneMode=places
SplitterPos=368

**Comment by kellerleicheorig** [comment] 2016-12-22 19:56
Found the issues now...
If I using single click, i get the problem with move here...

diff -uNr pcmanfm-qt.orig/lxqt/settings.conf pcmanfm-qt/lxqt/settings.conf
--- pcmanfm-qt.orig/lxqt/settings.conf	2016-12-22 20:32:13.701937774 +0100
+++ pcmanfm-qt/lxqt/settings.conf	2016-12-22 20:46:42.372212247 +0100
@@ -5,7 +5,7 @@
 ConfirmTrash=false
 NoUsbTrash=false
 QuickExec=false
-SingleClick=true
+SingleClick=false
 UseTrash=true

**Comment by agaida** [comment] 2016-12-22 19:58
i understand the problem but can't reproduce it -  works for me™ - and i might sound stubborn as usual but we need at least:
* Distribution
* Versions (pcmanf-qt, libfm-qt, libfm, Qt should be sufficient)
* that was exactly the meaning of "Gehts nicht noch knapper!"

**Comment by kellerleicheorig** [comment] 2016-12-22 20:21
My System is PCLinuxOS with LTS-Kernel 4.4.36

pcmanfm-qt, and libfm-qt are version 0.11.2 
libfm is 1.2.4, and QT is 5.6.2

Okay this is really strange, I will do some tests

**Comment by tsujan** [comment] 2016-12-22 20:24
@kellerleicheorig 
Your pcmanfm-qt is up-to-date enough.

I can't reproduce your problem with single-click either. Are you sure that you had read-and-write permission for the file you wanted to move?

**Comment by kellerleicheorig** [comment] 2016-12-22 20:26
Yes I have, it is the same file, and the same folder did you see in my video. With single-click wont move...

**Comment by agaida** [comment] 2016-12-22 20:47
@tsujan  5.6? But i never heard it before

**Comment by tsujan** [comment] 2016-12-22 21:05
> @tsujan 5.6? But i never heard it before

Qt-5.6 can't cause such a problem. His pcmanfm-qt is v0.11.2.

**Comment by agaida** [comment] 2016-12-22 21:37
strange

**Comment by pmattern** [comment] 2017-02-25 19:13
I can reproduce the problem running yesterday's master checkouts of all LXQt components on up to date Arch Linux.
Unfortunately it isn't reproducible 100% and so far I failed to figure out the exact conditions when it takes place. The locale does not seem to be the culprit as it can also be seen with `en_US.UTF-8`. But that aside no clue. When repeated attempts are made to move the file it sometimes works and sometimes it doesn't. Weird.

**Comment by MarcusE1W** [comment] 2017-05-03 17:24
Same problem hers as illustraded in the video.
With single click it won't work, with double click setting it does work.
I am using up to date archlinux and pcmanfm-qt 0.11.3

**Comment by tsujan** [comment] 2018-07-15 06:36
This may be an issue in installation of Qt translations.

**Comment by agaida** [comment] 2018-10-05 23:39
I will close this now - if anyone think there is stll a bug please re-open after checked it against latest git.

**Closed by agaida** 2018-10-05 23:39 UTC
