### ISSUE TITLE
Libfm-qt should support dektop entries linking to URL with any protocol

### ISSUE THREAD

**Issue by pols12** [lxqt/pcmanfm-qt#1065] opened 2020-02-01 16:28 UTC
I would like to create a desktop file which would point to a website.
Please consider the following desktop file:
```ini
[Desktop Entry]
Type=Link
URL=http://perdu.com
Name=Test
```
Execute it from pcmanfm-qt.

##### Expected Behavior
The web browser opens and goes to http://perdu.com

##### Current Behavior
pcmanfm-qt display a warning: `Invalid desktop entry file: 'http://perdu.com'`

##### Context
My `~/.config/mimeapps.list` contains:
```ini
[Default Applications]
x-scheme-handler/http=firefox-esr.desktop;
x-scheme-handler/https=firefox-esr.desktop;
```

##### System Information

* Distribution & Version: Debian GNU/Linux 10.2
* Kernel: 4.19.0-6-amd64
* Qt Version: 5.11.3
* libfm-qt Version: 0.14.1
* libqtxdg Version: libqt5xdg3 3.3.1
* lxqt-build-tools Version: not installed
* Package version: 0.14.1

**Comment by wxl** [comment] 2020-02-01 16:42
Interestingly, if one quotes the URL, it forgoes the error but then attempts to look in the file structure for it with an error like:

    Error getting information for file "/home/someuser/"http:/perdu.com"": No such file or directory

Workaround: change it to `Type=Application` with `Exec=x-www-browser URL`.

Still, if we are to adhere to the Desktop Entry Specification, we should support the link type.

**Comment by tsujan** [comment] 2020-02-01 17:13
Since Nautilus can't open those links either (I installed its latest version, tried it and uninstalled it right now), I think it may be a problem in GLib.

But I agree that the expected behavior is what's described in this report. Should look into the code...

**Comment by tsujan** [comment] 2020-02-01 17:17
BTW, as a workaround, you could set `Type=Application` and use `Exec=gio open https://...` or, if you don't have `gio`, `Exec=xdg-open  https://...`. @wxl's suggestion should work too.

**Comment by wxl** [comment] 2020-02-01 17:18
@tsujan LXDE pcmanfm has no problem with it.

**Comment by tsujan** [comment] 2020-02-01 17:21
> @tsujan LXDE pcmanfm has no problem with it.

Our code is very different. I don't think it's difficult to implement.

Strangely, I saw no bug report against Nautilus, but that doesn't concern us.

**Comment by wxl** [comment] 2020-02-01 17:22
@tsujan Understood. I was responding to your suspicion about GLib.

**Comment by tsujan** [comment] 2020-02-01 17:36
> I was responding to your suspicion about GLib.

My suspicion was only a gut feeling ("Why should Nautilus have the same problem?"). It's also possible that our code has a bug. I'll investigate it soon (maybe, not today).

**Comment by agaida** [comment] 2020-02-01 18:33
Please see an url as some kind of file and please rememver too that we follow the xdg specs native as possible. open any url or any other "file" is clearly a job for xdg-open as @tsujan suggested, so i close this bug here

**Comment by wxl** [comment] 2020-02-01 18:37
@agaida that's the equivalent of saying "we make sure to open `Type=Link` Desktop Entries" while at the same time saying "we don't bother trying to open `Type=Link` Desktop Entries." @tsujan suggested, like I did, a workaround to a bug implementing the Desktop Entry Speciifications. I can also use "Connect to Server" to open a link, but is it `xdg-open` doing that? No…

**Comment by tsujan** [comment] 2020-02-01 18:52
@agaida IMHO, this is a valid bug report. I'll either reopen it when I find the fix or explain why it can't be fixed but, most probably, it's fixable.

**Comment by agaida** [comment] 2020-02-01 19:10
if i miss something, but ...

```
~ % cat Desktop/testurl.desktop
[Desktop Entry]
Name=urltest
GenericName=urltest
Exec=xdg-open https://siduction.org
Terminal=false
Type=Application
```

**Comment by wxl** [comment] 2020-02-01 19:19
Yes, that works, but you are missing something. Please read the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/) to see what you're missing.

"This specification defines 3 types of desktop entries: Application (type 1), Link (type 2) and Directory (type 3)."

**Comment by tsujan** [comment] 2020-02-01 19:21
@agaida That's completely correct but a URL should also be opened with `Type=Link`.

Good news: I had a little time and found the problem: we didn't consider one case in the code. I included it and the file was opened in browser.

The previous code needs a little cleanup and I should also see if my fix is the best way. Tomorrow, I'll have enough time to do both :)

**Comment by agaida** [comment] 2020-02-01 21:01
ok, fine :)

**Comment by tsujan** [comment] 2020-02-01 23:56
The fix is here (now it's tomorrow): https://github.com/lxqt/libfm-qt/pull/519

Please read what comes after "NOTE:" (in the PR message).

**Closed** 2020-02-22 17:46 UTC
Labels: bug
