### ISSUE TITLE
Eject button is missing sometimes

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#443] opened 2017-01-22 15:57 UTC
With pcman 0.11.3 (on an Arch/Fluxbox system) under Devices I've got two entries: Filesystem and my external USB (mounted by `udisksctl mount…` command in my Fluxbox startup file). But instead of having eject image next to my external USB I have it next to Filesystem on pcman side panel.

**Comment by tsujan** [comment] 2017-01-22 16:12
This can be devided into two issues:

(1) Yes, there's an eject button next to the root partiton and that's misleading but it's safe because you couldn't unmount the partition is question.

(2) Is the USB really mounted *by pcmanfm-qt* (in fact, by libfm)? Doesn't the eject button appear when you *open* it in pcmanfm-qt?

**Comment by AcarBurak** [comment] 2017-01-22 16:56
(2) USB is mounted, as I've mentioned, by 'udisksctl mount…' command put in my Fluxbox startup file and no, eject button doesn't appear in pcmanfm-qt, probably because I haven't mounted it by the lxqt way, by solid or something. But anyway, since on context menu there's an unmount option, this is really another cosmetic glitch, not really an issue.

**Comment by tsujan** [comment] 2017-01-22 17:08
It's a (minor) bug. If there's an unmount menu item, there should be an eject button too. Will look into it. Thanks for reporting!

**Comment by tsujan** [comment] 2017-01-23 04:36
A note to myself for further investigation:

There's an interesting comment (by @PCMan?) in `libfm-qt` → `placesmodel.cpp` → `PlacesModel::onVolumeAdded`, which says, *".. .sometimes we get repeated volume-added signals and add a device more than once..."* Maybe, in such cases, the first signal is sent when `g_volume_get_mount()` is still NULL. `libfm-qt` processes only the first signal; hence the missing eject icon in some cases. That's while the context menu is opened when all signals are sent.

**Comment by tsujan** [comment] 2018-05-10 08:47
I've seen mounted USB without the eject button just a few times since this issue was opened. There's definitely an issue but so hard to reproduce. The only way for finding the cause may be reading the pertinent codes line by line -- too time-consuming...

**Comment by AcarBurak** [comment] 2018-05-10 12:13
Now I see eject images next to all. Please feel free to close this.

**Comment by tsujan** [comment] 2018-05-10 17:27
I've missed them 2-3 times with USB sticks. So, there may be a small mistake in the code.

**Comment by tsujan** [comment] 2018-07-15 06:33
I really should investigate this issue (encountered it again) but every time, I find a more urgent problem to fix.

**Closed** 2018-10-09 20:55 UTC
Labels: bug
