### ISSUE TITLE
Go ~ home after anything other than pcmanfm-qt unmounts/ejects a device/volume

### ISSUE THREAD

**Issue by grahamperrin** [lxqt/pcmanfm-qt#1279] opened 2020-12-30 18:45 UTC
Building upon #42

From <https://github.com/helloSystem/hello/issues/50#issuecomment-752715895>: 

![image](https://user-images.githubusercontent.com/192271/103373024-ab701d00-4acb-11eb-9720-6bb515602dcc.png)

Whilst the device is no longer listed: 

* the path (no longer available) remains in the address bar
* the directory content (no longer available) remains in the window. 

The _helloSystem_ pictured is `FreeBSD 13.0-CURRENT #0 …(main)-dirty: Thu Dec 24 06:21:50 UTC 2020`. 

Re: https://www.freshports.org/x11-fm/pcmanfm-qt/ I'll e-mail the maintainer with reference to this issue.

**Comment by tsujan** [comment] 2020-12-30 18:57
I'm closing this because your report doesn't make sense. *Follow the issue template, PLEASE!*

I'll reopen the report if you correct it.

**Closed by tsujan** 2020-12-30 18:57 UTC

**Comment by tsujan** [comment] 2020-12-30 19:04
Oh, forget about correcting the report! You don't use pcmanfm-qt but "Filer", belonging to "helloSystem". It has nothing to do with us.

**Comment by grahamperrin** [comment] 2020-12-31 06:39
Apologies for not using the template. 

https://github.com/helloSystem/hello/issues/50#issuecomment-752400387

> … pcmanfm-qt which Filer is currently based on

**Comment by tsujan** [comment] 2020-12-31 06:48
> pcmanfm-qt which Filer is currently based on

LXQt isn't responsible for forks.

> I see the same behaviour with pcmanfm-qt 0.16.0 on FreeBSD-CURRENT:

Which behavior?! The template is there for not wasting time with guesses and "telepathy".

**Comment by grahamperrin** [comment] 2020-12-31 06:49
Edited. Apologies for the waste of time.

**Comment by tsujan** [comment] 2020-12-31 06:51
> the device remains in the sidebar after umount...

Not reproducible.

Have you installed all `gvfs` packages?

**Comment by probonopd** [comment] 2021-10-17 09:15
@tsujan have you ever seen `computer:///...drive` items show up in `computer://`? I think these are causing this. Unfortunately I cannot reliably reproduce the issue, but _sometimes_ I had  `computer:///...drive` items show up there. So I'd like to prevent those from being created, or at least filter them out before they reach pcmanfm-qt (or Filer which is based upon it).
