### ISSUE TITLE
Folder actions create a crash 

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#673] opened 2018-05-15 21:31 UTC
Qt 5.11 rc 1 - even a double click at the desktop is sufficient to make pcmanfm-qt crash - latest git in ArchLinux.

@tsujan - might be worth a look

```
Thread 1 "pcmanfm-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff7551abc in Fm::ProxyFolderModel::filterAcceptsRow(int, QModelIndex const&) const () from /usr/lib/libfm-qt.so.5
(gdb) bt
#0  0x00007ffff7551abc in Fm::ProxyFolderModel::filterAcceptsRow(int, QModelIndex const&) const () at /usr/lib/libfm-qt.so.5
#1  0x00007ffff5ded138 in  () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff5def2fd in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff5defee9 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff5e38a0c in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff5dc1caf in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff5dc979c in QAbstractItemModel::endInsertRows() () at /usr/lib/libQt5Core.so.5
#7  0x00007ffff754a8bf in Fm::FolderModel::onFilesAdded(Fm::FileInfoList const&) () at /usr/lib/libfm-qt.so.5
#8  0x00007ffff5e38b60 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#9  0x00007ffff7539545 in Fm::Folder::filesAdded(Fm::FileInfoList&) () at /usr/lib/libfm-qt.so.5
#10 0x00007ffff74ebb79 in Fm::Folder::onDirListFinished() () at /usr/lib/libfm-qt.so.5
#11 0x00007ffff5e392e2 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#12 0x00007ffff6b7e984 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff6b8625b in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff5e0ebc9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff5e11c5c in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#16 0x00007ffff5e62864 in  () at /usr/lib/libQt5Core.so.5
#17 0x00007ffff509c368 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff509c5b1 in  () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff509c63e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff5e61e49 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#21 0x00007fffecc10b32 in  () at /usr/lib/libQt5XcbQpa.so.5
#22 0x00007ffff5e0d85c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#23 0x00007ffff5e15b56 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#24 0x0000555555575b81 in main ()
(gdb) quit


```

**Comment by tsujan** [comment] 2018-05-17 08:59
Duplicate of https://github.com/lxqt/libfm-qt/issues/164

**Closed by tsujan** 2018-05-17 08:59 UTC
