### ISSUE TITLE
Menu spawned by menu key differs from right click menu in detail list mode

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#1882] opened 2024-03-18 11:42 UTC
##### Expected Behavior

File context menu should be the same when spawn by right click and by menu key.

##### Current Behavior

File associations are different (like for a text file), archiver integration commands are different (only "Compress" is available, no "Extract*" options).

Properties option opens properties of the correct file, so this is not an issue with focus.

##### Steps to Reproduce (for bugs)

1. Focus a `.zip` file
2. Press menu key

##### System Information

* PcManFm-qt version: 1.4.0
* Distribution & Version: Debian Sid
* Qt Version: 5.15.10
* liblxqt Version: 1.4.0

**Comment by tsujan** [comment] 2024-03-18 11:59
> Menu spawned by menu key differs from right click menu

Not reproducible. Could you attach screenshots of *the context menus of the same file* popped up by right clicking and the menu key?

> only "Compress" is available, no "Extract*" options

Again, not reproducible.  What do you have in Preferences → Advanced → Archiver integration?

**Comment by Vladimir-csp** [comment] 2024-03-18 12:11
Top: right click, bottom: menu key:
![image](https://github.com/lxqt/pcmanfm-qt/assets/4061903/7e5a8f50-df35-47a5-b9bf-0a9ad4f729cf)

Archiver integration: tried lqxt-archiver and arqiver, no difference.

Not reproducible in 1.3.0.

**Comment by tsujan** [comment] 2024-03-18 12:20
Thanks! Your screenshot shows an additional and important piece of info: the detailed list mode. Indeed, I can reproduce the issue in that mode; the other modes aren't affected (can you confirm that?).

**Comment by tsujan** [comment] 2024-03-18 13:22
Either this is an old bug, or it should be about a change in a recent version of Qt, because the relevant code hasn't changed since 1.3.0.

The cursor position is reported differently when the context menu is shown by Menu key. The result depends on where the selected file is among other files. and especially on the file(s) before it.

**Comment by tsujan** [comment] 2024-03-18 15:18
I checked the code. This is a Qt bug: the cursor position reported by `contextMenuEvent` is above the real position when Menu key is used.

I'm not sure whether a safe workaround is possible.

**Comment by Vladimir-csp** [comment] 2024-03-18 15:22
Why properties item opens properties for the correct file? Cursor position updates after menu is open?

**Comment by tsujan** [comment] 2024-03-18 15:40
> Why properties item opens properties for the correct file?

Because, in our code, it checks the selected file, not the cursor position.

Only the open-with and archiving menu-items consult the cursor position (indirectly), which is reported incorrectly by Qt when the view contains a `QTreeView` (= our list view) and the context menu is opened by Menu key.

**Comment by tsujan** [comment] 2024-03-18 15:57
This screenshot shows how ridiculous the situation can be. Here, the context menu is opened by Menu key:

![menu_key](https://github.com/lxqt/pcmanfm-qt/assets/981076/75931184-6119-4638-80ec-ecf34c8bad2b)

My installed archive managers are shown in the open-with menu because the reported cursor position belongs to the row immediately above the selected row, although if I click on one of those archive managers, they'll correctly say that they can't open a text file.

**Comment by tsujan** [comment] 2024-03-18 18:08
I found a safe and small workaround: https://github.com/lxqt/libfm-qt/pull/960

The workaround will be in LXQt 2.0.0 (we've already ported libfm-qt and pcmanfm-qt to Qt6 in git), but distros/users can apply the patch to 1.4.0 too.

Thanks for reporting!

**Closed** 2024-03-23 13:12 UTC
Labels: Qt bug
