### ISSUE TITLE
Problem with mime association

### ISSUE THREAD

**Issue by Bezzumnbiu** [lxqt/pcmanfm-qt#1243] opened 2020-11-19 14:54 UTC
##### Expected Behavior

When you change the association to file, the association is applied to the file

##### Current Behavior

When the association is applied, the file "-mimeapps.list" is created instead of "mimeapps.list"

##### Possible Solution

Use link with "-rs" argument 
##### Steps to Reproduce (for bugs)

1. Use 0.16.0 version pcmanfm-qt

##### System Information

* Distribution & Version: Arch Linux
* Kernel: Linux-zen 5.9.8-zen1
* Qt Version: 5
* libfm-qt Version: 1.3.1-2
* libqtxdg Version: 3.6.0-1
* lxqt-build-tools Version: 0.8.0-1
* Package version: 0.16.0

**Comment by tsujan** [comment] 2020-11-19 15:06
Interesting! What's the output of this in a terminal?
```sh
echo $XDG_CURRENT_DESKTOP
```

**Comment by tsujan** [comment] 2020-11-20 16:35
I simulated your situaction in a terminal by setting `XDG_CURRENT_DESKTOP` to `:BLAH`. Then I gave C++ files to Kate in pcmanfm-qt (they were assigned to FeatherPad). All C++ files were opened by Kate afterward, as expected. In other words, "-mimeapps.list" was created and respected — again, as expected.

File association tools should use "$desktop-mimeapps.list" for overriding associations *in the current DE*, without affecting other DE's associations (see https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html). pcmanfm-qt didn't dollow this rule before but that's fixed in 0.16.

In your case, for whatever reason, `XDG_CURRENT_DESKTOP` is `:WHATEVER`; so, "-mimeapps.list" is created to override associations. And contrary to the first sentence of your report, the file association is really applied.

**Closed by tsujan** 2020-11-20 16:35 UTC

**Comment by tsujan** [comment] 2020-11-20 16:38
BTW, if `XDG_CURRENT_DESKTOP` was correct in your case, you would see `lxqt-mimeapps.list` or `kde-mimeapps.list` or..., depending on the DE, under which you use pcmanfm-qt. However, file association still works.

**Comment by bxkx** [comment] 2021-09-25 17:51
I'm having the same problem. pcmanfm-qt creates and updates -mimeapps.list, but reads from mimeapps.list

echo $XDG_CURRENT_DESKTOP returns nothing/an empty line

**Comment by tsujan** [comment] 2021-09-25 18:05
> ... but reads from mimeapps.list

Rread [above](https://github.com/lxqt/pcmanfm-qt/issues/1243#issuecomment-731272800). You may have an old version (< 0.16).

**Comment by bxkx** [comment] 2021-09-25 21:00
I'm on 0.17.0

**Comment by tsujan** [comment] 2021-09-26 15:07
> I'm on 0.17.0

I can't reproduce the problem that's mentioned here but, maybe, you've found another problem. Please open an issue and add all relevant info to it, *especially the way of reproducing*.

**Comment by tsujan** [comment] 2022-01-02 05:55
GLib's behavior may have changed since 2020 (when I tested) or I might have made a mistake (sorry if the latter is the case!). Anyway, [the issue was reported again](https://github.com/lxqt/pcmanfm-qt/issues/1510) and [fixed](https://github.com/lxqt/libfm-qt/pull/766). Sadly, the fix can't be included in LXQt 1.0.0; it'll be in 1.1.0.
