### ISSUE TITLE
pcmanfm-qt 1.1.0 fail to open smb because it try dnssd-domain-host._smb._tcp instead smb://host

### ISSUE THREAD

**Issue by edefranco** [lxqt/pcmanfm-qt#1658] opened 2022-09-18 16:46 UTC
##### Expected Behavior

clicking on the icon of the discovered network shared directory it should be open it
##### Current Behavior

opening pcmanfm-qt network on desktop, it show correctly the share but clicking on it failed to open. If you type manually the path in address bar with smb://host/share/ it open regularly the network directory. The icon of the shared point to dnssd-domain-[shared name]._smb._tcp instead smb://host/shared name/
##### Possible Solution

correct the errate behaviour as described with the correct string smb://host/shared name discovered/
##### Steps to Reproduce (for bugs)

1. click on network icon on the lxqt desktop
2. click on one host name discovered
3.
4.

##### Context

I searched solution on google but not found.
##### System Information

* PcManFm-qt version: 1.1.0
* Distribution & Version: Lubuntu 22.04.01 LTS X86_64
* Qt Version:
* liblxqt Version: 1.1.0

**Comment by tsujan** [comment] 2022-09-18 19:29
I only see a "Windows Network" icon  with path `network:///`, that opens an empty `smb:///`, although I can access my shares by entering their paths (and creating bookmarks). Please be more specific about your SMB setup and how those items are created for you. A screenshot would also be appreciated.


But, more importantly, since what's under Network is created by GLib + GVFS, do you see a different behavior under Nautilus or, perhaps, another GLib-based file manager?

**Comment by edefranco** [comment] 2022-09-19 17:00
Actually I am running Lubuntu on VMWare player. The host pc were the vm is hosted have some smb share in workgroup. On the network I have not other smb sharing for this I can test it only with this pc.
As you can view in the following screenshot 

![screen](https://user-images.githubusercontent.com/63565376/191067048-7b896265-af23-4349-a1fb-e362e7813fe2.jpg)

when I open network link pcmanfm-qt on my desktop, I see correctly the share host.
If I click on the icon of the share, after about 5 second, I obtain a dialog that tell me that it cannot find the connections list from the server because the connection are refused. 

![screen1](https://user-images.githubusercontent.com/63565376/191068119-7b25abe6-c78f-42ee-ae96-8d254feaad10.jpg)

Clicking now on ok, after short time it show another dialog that tell me that the position specified is not mounted.

![screen2](https://user-images.githubusercontent.com/63565376/191068434-ebf5060c-748f-4221-a8a9-f5c19f6aa404.jpg)

If I right click on the icon of the host and select "properties", I view that it point to incorrect position:

![screen3](https://user-images.githubusercontent.com/63565376/191069296-8396af57-cd68-4f0b-99b1-cf299833b732.jpg)

It should be smb://etel-113-02/ and not dnssd-domain-host._smb._tcp !
If I write smb://etel-113-02/ (-> please note smb:// not smb:/// <-) into the address bar, it open regularly the share.

![screen4](https://user-images.githubusercontent.com/63565376/191070340-5495522a-5e73-441c-9025-aff459e6a3fc.jpg)

At the moment I have not checked other network browser because I would like create a light-weight distro to put on a USBKEY and pcmanfm-qt are the right chose ... but if you want I can install it and try ...
I don't know how pcmanfm-qt get the host name but is evident that it get correctly the host name but elaborate it incorrectly to open the share ... what is dnssd-domain-host._smb._tcp ?? where does it come from ?

I have no idea ... 

Thank in advance for any suggestion about ... 

Emilio

**Comment by tsujan** [comment] 2022-09-19 18:10
Thanks for the screenshots.

Since pcmanfm-qt doesn't create those items (it just shows them as they are), that incorrect position isn't created by it. VMWare should be the cause.

I asked you to check the same item with Nautilus to see that the problem is independent of the file manager.

Closing this for now. You could add comments though.

**Closed by tsujan** 2022-09-19 18:10 UTC
