### ISSUE TITLE
Encrypted USB Volume - Freeze / Hang on Password Dialog

### ISSUE THREAD

**Issue by aphirst** [lxqt/pcmanfm-qt#1106] opened 2020-04-27 20:27 UTC
##### Expected Behavior

I expect to be able to click on an encrypted volume on the side panel, be given the password dialogue, be able to type in the password, and for the volume to mount.

##### Current Behavior

I click on the encrypted volume in the side panel, I get the password dialogue, but pcmanfm-qt freezes after about one second. `xkill` and `killall pcmanfm-qt` both fail, I have to kill from inside `htop` before I can re-open pcmanfm-qt.

##### Steps to Reproduce (for bugs)

1. Create a new encrypted volume on a USB disk (in my case a Seagate 4TB USB3 disk) using, say, `# cryptsetup -v luksFormat /dev/xxx`
2. Open pcmanfm-qt, click on the Encrypted Volume in the left-hand panel
3. See the password dialogue, and either try to type, or just wait
4. pcmanfm-qt is now hung

##### System Information

* Distribution & Version: Arch Linux (x86_64)
* Kernel: 5.5.19-1-ck-ivybridge
* Qt Version: 5.14.2-1
* libfm-qt Version: 0.15.0-1
* libqtxdg Version: I don't think this is installed?
* lxqt-build-tools Version: 0.7.0-1
* Package version: 0.15.0-2
I'm not using lxqt itself, just pcmanfm-qt. I don't have any "DE", just openbox and some individual environment stuff.

**Comment by aphirst** [comment] 2020-04-27 20:30
A user called @daniel-s made a similar report on the lxqt page which was closed due to an inability to reproduce it. https://github.com/lxqt/lxqt/issues/1757

**Comment by tsujan** [comment] 2020-04-27 20:36
> A user called @daniel-s made a similar report on the lxqt page....

You could have added a backtrace on that page. Crash reports should be accompanied by backtraces when developers can't reproduce them.

I close this too but, if you attach a correct backtrace, I'll reopen it (see Arch Wiki on how to create a backtrace).

**Comment by aphirst** [comment] 2020-04-27 20:39
Do you need the backtrace just for pcmanfm-qt or also for libfm-qt?

**Comment by tsujan** [comment] 2020-04-27 20:42
The one that crashes. See `/var/lib/systemd/coredump`, issue `coredumpctl gdb APP_NAME`, then `where`, and attach what comes after `where`.

**Comment by aphirst** [comment] 2020-04-27 21:03
It doesn't segfault, it just hangs. Would that even generate a coredump?
Also in order to rebuild libfm-qt and pcmanfm-qt I need the GPG key for the source files, but I seem to be having problems.
```
$ gpg --recv-keys BE793007AD22DF7E
gpg: keyserver receive failed: No keyserver available
```
I tried with a load of manual `--keyserver` entries but no luck yet.

**Comment by tsujan** [comment] 2020-04-27 21:19
> Would that even generate a coredump?

No.

> Also in order to rebuild libfm-qt and pcmanfm-qt I need the GPG key for the source files, but I seem to be having problems.

Use Arch's PKGBUILD but re-building what's already in Arch won't make a difference.

I'll test again later, on two machines.

**Comment by aphirst** [comment] 2020-04-27 21:21
Re-building it with `options=(debug !strip)` in the PKGBUILD on the other hand, should, which is what I did.
A clarification of the problem: like all the best problems, it's not deterministic. If I keep killing pcmanfm-qt and trying to mount the encrypted volume, the password-dialog freeze occurs probably 3/4 times.

**Comment by tsujan** [comment] 2020-04-27 21:27
> it's not deterministic.

Some bugs are so -- hard to reproduce, hard to track. I'll try my best to reproduce it; once will be enough.

**Comment by tsujan** [comment] 2020-04-27 22:15
@aphirst 
I tested on 2 machines several times. I even entered wrong passwords and then the correct one to see what happens. Everything was OK.

Conclusion: A piece of info should be missing from your report.

**Comment by aphirst** [comment] 2020-04-27 22:23
I can't think of anything I'm specifically missing from my report. I really did literally just make the encrypted volume, and the dialog really does sometimes **just** freeze and lock up the entire application.
I can run pcmanfm-qt (with symbols) in gdb if you can tell me what to do to get info once it hangs?

**Comment by tsujan** [comment] 2020-04-27 22:33
Stop pcmanfm-qt's process in Session Settings, Issue `gdb pcmanfm-qt` in a terminal, type `run`, wait for the hang to happen, paste the lines that lead to the hang.

**Comment by aphirst** [comment] 2020-04-27 22:36
I guess this info isn't useful:
```
Reading symbols from pcmanfm-qt...
(gdb) run
Starting program: /usr/bin/pcmanfm-qt 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff22d0700 (LWP 19561)]
qt5ct: using qt5ct plugin
[New Thread 0x7fffebfff700 (LWP 19562)]
[New Thread 0x7fffea49a700 (LWP 19564)]
[New Thread 0x7fffe9c99700 (LWP 19565)]
[New Thread 0x7fffe9498700 (LWP 19566)]
[New Thread 0x7fffe8c97700 (LWP 19567)]
isPrimaryInstance
[New Thread 0x7fffd2c9b700 (LWP 19569)]
[Thread 0x7fffd2c9b700 (LWP 19569) exited]
qt5ct: D-Bus global menu: no
[New Thread 0x7fffd2c9b700 (LWP 19570)]
[New Thread 0x7fffd249a700 (LWP 19571)]
[New Thread 0x7fffd1c99700 (LWP 19572)]
[New Thread 0x7fffc3fff700 (LWP 19573)]
[New Thread 0x7fffc37fe700 (LWP 19574)]
[New Thread 0x7fffc2ffd700 (LWP 19575)]
[New Thread 0x7fffc27fc700 (LWP 19576)]
[Thread 0x7fffd1c99700 (LWP 19572) exited]
[Thread 0x7fffd2c9b700 (LWP 19570) exited]
[New Thread 0x7fffd1c99700 (LWP 19577)]
[Thread 0x7fffd249a700 (LWP 19571) exited]
[Thread 0x7fffe9498700 (LWP 19566) exited]
[New Thread 0x7fffd1c99700 (LWP 19578)]
[Thread 0x7fffd1c99700 (LWP 19577) exited]
ask password
```

**Comment by aphirst** [comment] 2020-04-27 22:40
I reproduced the crash and ran `thread apply all bt full` in gdb, and got this output:
https://pastebin.com/x7ttPV8S

**Comment by tsujan** [comment] 2020-04-27 22:50
It just waits for the mount -- as it should -- but nothing happens. The cause may be outside libfm-qt. All gvfs packages installed?

**Comment by aphirst** [comment] 2020-04-27 22:56
I have all the ones I thought I needed:
```
[adam@shimmer ~]$ pacman -Ss gvfs
extra/gvfs 1.44.1-1 (gnome) [installed]
    Virtual filesystem implementation for GIO
extra/gvfs-afc 1.44.1-1 (gnome) [installed]
    Virtual filesystem implementation for GIO (AFC backend; Apple mobile devices)
extra/gvfs-goa 1.44.1-1 (gnome)
    Virtual filesystem implementation for GIO (Gnome Online Accounts backend; cloud storage)
extra/gvfs-google 1.44.1-1 (gnome)
    Virtual filesystem implementation for GIO (Google Drive backend)
extra/gvfs-gphoto2 1.44.1-1 (gnome)
    Virtual filesystem implementation for GIO (gphoto2 backend; PTP camera, MTP media player)
extra/gvfs-mtp 1.44.1-1 (gnome) [installed]
    Virtual filesystem implementation for GIO (MTP backend; Android, media player)
extra/gvfs-nfs 1.44.1-1 (gnome) [installed]
    Virtual filesystem implementation for GIO (NFS backend)
extra/gvfs-smb 1.44.1-1 (gnome) [installed]
    Virtual filesystem implementation for GIO (SMB/CIFS backend; Windows client)
```

While reproducing the bug, I notice something strange. If trying to mount the encrypted disk is the first thing I do in pcmanfm-qt, the password dialog tends to freeze the program. However, if I start mounting other disks, browsing around other folders, or sit in a folder which is generating thumbnails, the password dialog tends to not freeze.

**Comment by tsujan** [comment] 2020-04-27 23:02
libfm-qt blocks by using an internal `QEventLoop` until the whole mount operation is finished. That's the normal behavior because we should wait for mounting to be finished (correctly or incorrectly). The problem is that, in your case, the mount operation is never finished (it neither finishes with an error) for a reason that's still unknown.

**Comment by aphirst** [comment] 2020-04-27 23:10
To reiterate, the problem occurs with the password dialog irrespective of whether anything was typed, or whether you actually attempt the mount. The password dialog itself causes everything to freeze - no input required.

**Comment by tsujan** [comment] 2020-04-27 23:19
> To reiterate, the problem occurs with the password dialog irrespective of whether anything was typed

Attach a screenshot of the password dialog when it hangs -- although I'm not saying that a miracle will happen when I see it ;)

For now, I have no idea. It's very hard -- if not impossible -- to solve a problem that one doesn't see. And it's late here. Maybe tomorrow.

**Comment by aphirst** [comment] 2020-04-27 23:25
Is the password dialogue coming from pcmanfm-qt itself, or is it coming from whatever keyring manager I have installed?
![nice2](https://user-images.githubusercontent.com/1735556/80430527-bc3a1480-88e6-11ea-965b-414996498b35.png)
`gnome-keyring 1:3.36.0-1`
`libgnome-keyring 3.12.0+13+g4f8ab73-1`

**Comment by tsujan** [comment] 2020-04-27 23:32
Thanks for all the info! You did a great job.

Unfortunately, everything seems OK. I couldn't find anything suspicious in your debug output either but I'll examine it again tomorrow.

**Comment by aphirst** [comment] 2020-04-27 23:34
Sorry I couldn't be more help. If you like, we could do something more interactive, maybe on IRC? (I'm `aphirst` pretty much everywhere.)

**Comment by tsujan** [comment] 2020-04-27 23:36
> Sorry I couldn't be more help.

You did much more than I could have expected :) *I* am sorry for not having a clue yet.

**Comment by tsujan** [comment] 2020-04-28 02:08
OK, after a short sleep, I found the missing info (not the solution yet):

 1. You have this option checked: "Mount mountable volumes automatically on startup".
 2. You don't use LXQt, which means you don't have pcmanfm-qt's daemon.
 3. You first insert the disk, then open a pcmanfm-qt window *but you don't wait for its password dialog to show up automatically* (it will after 3 seconds or so). instead, you click on the side-panel item.

After those 3 seconds pass, pcmanfm-qt wants to show the same dialog; hence the hang.

No wonder why I couldn't reproduce it: first, I use LXQt, so I have pcmanfm-qt's process running in thee background; second, even without pcmanfm-qt's desktop, I haven't checked the above-mentioned option.

Good news: LXQt users won't encounter this issue. Bad news: There is a bug; hence reopening.

**Comment by tsujan** [comment] 2020-04-28 07:16
@aphirst 
The fix is here: https://github.com/lxqt/pcmanfm-qt/pull/1108

Please test it!

**Comment by aphirst** [comment] 2020-04-28 07:53
Amazing news!

I built that specific commit, and it does seem to work. If I click the disk on the side, I get a password dialogue that doesn't seem to freeze; and if I close that dialogue, it comes up again (presumably from the automount feature) and that also doesn't seem to freeze.

I'll test this a bit more thoroughly today, but there's a good chance you've hit the nail on the head. Thanks an awful lot.

If I have any other issues to report, I'll try to more prominently state my usage scenario at the start to avoid some of this head-scratching.

**Comment by tsujan** [comment] 2020-04-28 08:09
> and if I close that dialogue, it comes up again (presumably from the automount feature) 

Exactly!

> If I have any other issues to report, I'll try to...

Your report was very good. The confusion was inevitable because the bug was of the most hidden ones I'd encountered.

I'll merge the PR after a few weeks and then make a point release. Thank you so much both for the report and for the test!

**Comment by selairi** [comment] 2020-05-02 15:17
I have tested the [https://github.com/lxqt/pcmanfm-qt/pull/1108](https://github.com/lxqt/pcmanfm-qt/pull/1108) commit:  Good work.

GTM.

**Comment by tsujan** [comment] 2020-05-02 18:56
@selairi Thanks! Will merge it tomorrow.

**Closed** 2020-05-03 05:03 UTC
Labels: bug
