### ISSUE TITLE
Recursive Moving of folders is prohibited in some cases

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#943] opened 2019-04-19 19:03 UTC
##### Expected Behavior
If i want to move a folder the folder should move.

##### Current Behavior
It don't  -  https://youtu.be/m5lV-GmJadI

Sidenote: If i chose copy instead of move everything is fine.

##### Possible Solution
fixing it

##### Steps to Reproduce (for bugs)
1.  bind mount $HOME/Downloads to somewhat
2.  bind mount $HOME/Desktop to somewhat
3.  voila

##### Context
seems to be another nice glitch in gio handling

##### System Information
* Distribution & Version:  Sid/latest git as usual

**Comment by tsujan** [comment] 2019-04-19 19:14
I can't reproduce it but something's very wrong here; need time to find a clue what it may be.

What do you mean by "bind mount X to somewhat"? X is mounted?

**Comment by agaida** [comment] 2019-04-19 19:17
- take a partition, mount it to /mnt/foo
- bind mount /mnt/foo/bar to $HOME/Desktop
- bind mount /mnt/foo/baz to $HOME/Downloads

test :P

**Comment by agaida** [comment] 2019-04-19 19:17
i try to simplify it a bit in a live system

**Comment by tsujan** [comment] 2019-04-19 19:27
Once I can reproduce it in a simple way, the rest will be straightforward (like the case of SMB).

P.S. I might not be able to think about it tonight but will tomorrow.

**Comment by agaida** [comment] 2019-04-19 19:28
ok, it is sufficent if both folders are bind mounted
```
cd /mnt
mkdir foo bar
chown $user:$user foo bar
mount -B /mnt/foo /home/$user/Downloads
mount -B /mnt/bar /home/$user/Desktop
```
re-login
download something (one of our tarballs) and extract in Downloads
try to move in pcmanfm-qt dual pane

**Comment by tsujan** [comment] 2019-04-19 19:37
Thanks! I'll do it in my other laptop. It the latest git libfm-qt and pcmanfm-qt.

**Comment by tsujan** [comment] 2019-04-19 20:41
The most important step done. Confirming. Very beautiful!

The second step: find where it happens in the code.

**Comment by tsujan** [comment] 2019-04-19 20:54
Second step done. The problem is in `FileTransferJob::moveFileSameFs()`. It's our fault because Nautilus doesn't have this issue.

**Comment by tsujan** [comment] 2019-04-19 21:11
OK, if it was possible before and this failure is new, it isn't our fault but a workaround may be possible. For some reason, Nautilus doesn't use `g_file_move` directly but iterates over the contents and move them instead.

@agaida Is this new?

**Comment by agaida** [comment] 2019-04-19 21:15
never encountered it before

**Comment by agaida** [comment] 2019-04-19 21:20
More verbose: i work with this setup for years now - / and /home on the same partition, directories in $HOME linked or mounted - that way i can use my files in every installation with different distribution and version specific things - so yes, it should work. Moving a directory in a filemanage is *not* so un-common.

**Comment by tsujan** [comment] 2019-04-19 21:21
So, something's changed in GLib. The only thing I need to find is that under which conditions we should copy & delete, instead of moving. Previously, it was enough that source and destination filesystems were identical; now, this condition isn't sufficient apparently.

**Comment by tsujan** [comment] 2019-04-19 23:54
OK, I didn't find a suitable condition -- tested all of them as far as I know -- but there's a simple workaround for this new inconvenience:

GLib sets the error code to `G_IO_ERROR_WOULD_RECURSE` in such cases. So, if this kind of error is encountered while moving, the code can ignore it and copy-delete the folder instead of moving it.

This is the easiest way and works fine. But I should give it more thought.

I think this problem happened at the same time when trashing became impossible with  `/mnt`.

**Comment by agaida** [comment] 2019-04-20 00:08
i guess you are right

**Comment by tsujan** [comment] 2019-04-20 17:39
OK, I'll make a PR for this tonight, after more tests. I really don't think it was our fault.

**Comment by tsujan** [comment] 2019-04-21 19:40
Done.

**Closed** 2019-04-26 19:21 UTC
Labels: bug
