### ISSUE TITLE
Cannot copy file content through ftp

### ISSUE THREAD

**Issue by R3G3N3R4T0R** [lxqt/pcmanfm-qt#994] opened 2019-08-14 03:49 UTC
##### Expected Behavior

If you use copy on a ftp directory folder and paste it on the hard drive of current computer both the folder and its content should be copied over to the hard drive.
##### Current Behavior

When you copy a folder through ftp to the current computer only the folder is copied over neglecting its content, leaving only an empty folder.
Individual files in the folder can still be copied over in a batch.

##### Steps to Reproduce (for bugs)

1. Connect to an ftp server (I used a local server ftp://192.168.0.102)
2. Copy any folder with content inside. (I mainly copy video files over)
3. Paste it in any directory on the current computer (eg. ~/Videos)

##### Context

This issue appeared before for smb(https://github.com/lxqt/pcmanfm-qt/issues/686) and the issue seems to be fixed but the ftp problem still exist. It is no major problem but it is inconvenient when you need to copy a lot of folders over ftp.
Sorry for the inconvenience but I know barely anything about linux
##### System Information

* Distribution & Version: Lubuntu 19.04
* Kernel: 5.0.0-25-generic
* Qt Version: 5.12.2
* libfm-qt Version:?
* libqtxdg Version: ?
* lxqt-build-tools Version: 0.14.1
* Package version: 0.14.1

**Comment by tsujan** [comment] 2019-08-14 03:58
Thanks for your report. The issue is already fixed in the git version. The fix will be in the next release.

**Closed by tsujan** 2019-08-14 03:58 UTC

**Comment by tsujan** [comment] 2019-08-14 06:00
> This issue appeared before for smb(#686) and the issue seems to be fixed but the ftp problem still exist. 

Oh, there may be a misunderstanding here. FTP and SFTP have never had this problem. The problem was in SMB and, perhaps, some other protocols but it's fixed (I'm sure about that but don't remember when I fixed it -- before or after 0.14.1).

I often use sftp to transfer files/folders between 2 laptops and have never had any problem with copying folder contents. Minutes ago, I also tried ftp and saw no problem: all of 102 files inside a folder (including a few subfolders and their contents) were copied alongside the folder itself, except for a symlink because FTP doesn't support symlinks.

So, the cause of your problem should be elsewhere.

**Comment by tsujan** [comment] 2019-08-14 06:29
Ah, the commit that fixed the recursive copying was https://github.com/lxqt/libfm-qt/commit/2fc359a71627ff19fd06654fd6de568f63225c58. In spite of its name, it isn't just about SMB and was made after V0.14.1.

Apparently, this shows 2 things:

 * FTP and SFTP have different behaviors (a surprise to me).
 * FTP is like SMB in this regard.
