### ISSUE TITLE
The order of open files is inverted

### ISSUE THREAD

**Issue by Dapid** [lxqt/pcmanfm-qt#902] opened 2019-02-21 12:11 UTC
##### Expected Behavior
I have a folder sorted by name with the files 01.mp3, 02.mp3, and 03.mp3. Selecting them all and opening on VLC I expect to play them in order, as happens with the LXDE version of pcmanfm.

##### Current Behavior
I get a playlist with 03, 02, and 01.

This is not restricted to VLC, the same applies when opening several images in GIMP.

##### Context
The workarounds are:
* Sort in descending order (03, 02, 01), so they open in the correct order.
* Open one by one.

##### System Information
The problem exists in two versions:

* Distribution & Version: Fedora 29 // Fedora 30 (beta)
* Kernel: 4.20.8-200 //  5.0.0-0.rc6.git1.1
* Qt Version:  5.11.3 // 5.11.3
* lxqt-build-tools Version:  0.5.0 // 0.6.0
* libqtxdg Version: 3.2.0 // 3.3.0
* liblxqt Version: 0.13.0 // 0.14.0
* libfm-qt Version: 0.13.0 // 0.14.0
* Package version: (?) (I am unsure what this means, but they are all installed from the repos).

**Comment by tsujan** [comment] 2019-02-21 17:27
OK, it's reproducible.

**Comment by tsujan** [comment] 2019-02-22 09:00
For the record:

There are 2 ways to fix this:

(1) Open files in the order they are selected by the user (the easy and more flexible way); or:
(2) Open files regardless of the order of selection and only according to the current sorting (Dolphin's way -- rigid).

I think (2) isn't good because it removes the possibility of changing the order without changing the sorting. (1) has this advantage that if the user selects files from start to end, they'll be opened in that order and, moreover, the user could change the order by selecting files in any order of his/her choice, without changing the sorting of the current folder.

**Comment by tsujan** [comment] 2019-02-22 09:26
Also, this may be needed to prevent confusion later:

pcmanfm-qt will respect the selection order when the user presses `Ctrl` (after the patch is created and merged) but the app may or may not respect that. For example, an app may open multiple files in the random order they can be loaded (small files may be loaded sooner) and another app may sort them itself.

**Closed** 2019-02-22 20:56 UTC
Labels: bug
