### ISSUE TITLE
Adding copy path back to context menu

### ISSUE THREAD

**Issue by randomlx** [lxqt/pcmanfm-qt#813] opened 2018-11-08 23:00 UTC
Copy-Path is no longer an option under the pcmanfm context menu.   Can it be brought back?  It's a very useful feature; it's sad to see it missing from the lxqt version.

If it can't be brought back, is there a hack that can be done by users to get it back under the context menu?  If so, maybe the instructions can be put in the user documentation for people who are sorely missing this option.

P.S.  I see that this was a feature asked for back in July, but there was never a good answer for why it is missing.  A supposed work-around to click on the path bar to copy the path has (so far) not worked for me in Lubuntu in a VM.  (Perhaps it's a VM issue, but I've tried three times already.)

**Comment by tsujan** [comment] 2018-11-08 23:07
No! Duplicate of a closed issue.

**Closed by tsujan** 2018-11-08 23:07 UTC
