### ISSUE TITLE
Auto activate tabs opened externally for single window mode.

### ISSUE THREAD

**Issue by Wobblystep** [lxqt/pcmanfm-qt#1165] opened 2020-07-20 12:53 UTC
With single window mode, I expect to be switched to tabs opened from Web browsers and desktop links automatically, because you know how it is, I really intended to go to that path. Just like "New tab" does.
Thanks for any help.

* Distribution & Version: Arch Linux;
* Kernel: 5.7.8-arch1-1
* Qt Version: 5.15.0
* libfm-qt Version: 0.15.1-2
* libqtxdg Version: 3.5.0-2
* lxqt-build-tools Version: 0.7.0-1
* Package version: 0.15.1-1

Edit: i have made searches through bugs, but couldnt find anything related before, sorry for making a duplicate to your question.
 apparently searching the following doesn't show your question issue i dont know:
  is:issue is:open tab

**Comment by tsujan** [comment] 2020-07-20 13:42
Duplicate of https://github.com/lxqt/pcmanfm-qt/issues/1110

**Closed by tsujan** 2020-07-20 13:42 UTC
