### ISSUE TITLE
Problem with file association when current desktop is empty

### ISSUE THREAD

**Issue by aryanprophet** [lxqt/pcmanfm-qt#1510] opened 2021-12-28 12:19 UTC
##### Expected Behavior
As example:
- When I double click to open a PNG file, it will open it with a Wine Internet Explorer.
- To change this behave, I right click on that file. Choose "Properties", then in the properties window, at the drop down box with label "Open With:", changing the value to "feh" or "lximage", then pressing Ok.
- When opening this Property dialog again... it should say "feh" or "lximage".

##### Current Behavior
As example:
- When I double click to open a PNG file, it will open it with a Wine Internet Explorer.
- To change this behave, I right click on that file. Choose "Properties", then in the properties window, at the drop down box with label "Open With:", changing the value to "feh" or "lximage", then pressing Ok.
- When opening this Property dialog again... it will still say "Wine Internet Explorer"

##### Possible Solution
- It seems like that pcmanfm-qt is saving the mime settings to the wrong file.
- Mime settings are saved to "-mimeapps.list", instead of "mimeapps.list".
- Renaming  "-mimeapps.list" to "mimeapps.list", applies ONLY the last changed settings.
- Double click on file opens it with correct application after renaming.
- On every change to mime settings, the renaming has to be repeated.

##### Steps to Reproduce (for bugs)
- See current behavior.

##### System Information
* PcManFm-qt version: pcmanfm-qt 1.0.0
* Distribution & Version: Linux version 5.15.11_1 (voidlinux@voidlinux) (gcc (GCC) 10.2.1 20201203, GNU ld (GNU Binutils) 2.35.1) #1 SMP Wed Dec 22 15:24:11 UTC 2021
* Qt Version: 5
* liblxqt Version:

**Comment by stefonarch** [comment] 2021-12-28 13:14
I cannot reproduce this. And settings are saved here in lxqt- mimeapps.list :
```
ls -l ~/.config/|grep mime
-rw-r--r--  1 stef stef  863 28 dic 14.10 lxqt-mimeapps.list
-rw-------  1 stef stef  641 10 dic 18.30 mimeapps.list
```
So there must be something in your installation that causes this. In which directory is your` mimeapps.list`  saved?

**Comment by tsujan** [comment] 2021-12-28 13:15
Thanks for your report!

> It seems like that pcmanfm-qt is saving the settings to the wrong file.

No. File association tools should use `$desktop-mimeapps.list` for overriding associations in the current DE, without affecting other DE's associations (see https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html). In your case, `XDG_CURRENT_DESKTOP` is empty; therefore, the association should be written to `-mimeapps.list`. In a normal LXQt session it's `lxqt-mimeapps.list`, while in KDE it's `kde-mimeapps.list`, etc.

However, there is a bug here: the association should be read from `-mimeapps.list` in your case, as it *is* read from `$desktop-mimeapps.list` when `$desktop` isn't empty. The bug happens only when `$desktop` is empty. Will fix that soon.

**Comment by tsujan** [comment] 2021-12-28 13:16
@stefonarch 
His desktop session name is empty. pcmanfm-qt writes to the correct file (namely, `-mimeapps.list`) but reads from `mimeapps.list`.

**Comment by stefonarch** [comment] 2021-12-28 13:16
Yeah I see and learned :)

**Comment by tsujan** [comment] 2021-12-28 13:22
We had a similar report. I closed it because I only considered the first half of it, which was an incorrect assumption. Fortunately, in this case, I didn't miss the second half.

**Comment by aryanprophet** [comment] 2021-12-28 13:36
Thank you very much for the info! Learned something.

My desktop is self compiled dwm from suckless.

When `XDG_CURRENT_DESKTOP` is empty, should it not read and write settings to `mimeapps.list` instead of `-mimeapps.list`?

Are you going to change it so it reads and writes to `mimeapps.list`?

Regards.

**Comment by tsujan** [comment] 2021-12-28 14:00
> When XDG_CURRENT_DESKTOP is empty, should it not read and write settings to mimeapps.list instead of -mimeapps.list?

Theoretically, it shouldn't.

However, I took a look at our code and found that there's a problem outside pcmanfm-qt. Sadly, GLib (which is used by pcmanfm-qt) only reads from `mimeapps.list` *when XDG_CURRENT_DESKTOP is empty*, and we can't change its behavior. Therefore, the situation should be reconsidered.

GLib documentation is silent about this but I checked its behavior. It drops the dash with an empty XDG_CURRENT_DESKTOP. So, we should drop it too, as you suggested.

I'll make a PR soon and explain everything in it.

**Comment by aryanprophet** [comment] 2021-12-28 14:04
Many thanks tsujan!

**Comment by tsujan** [comment] 2021-12-28 14:25
Thank *you* for reporting. If it wasn't for your detailed explanation, I wouldn't see the problem.

**Comment by tsujan** [comment] 2021-12-28 15:07
Fixed in https://github.com/lxqt/libfm-qt/pull/766

**Closed** 2021-12-28 15:07 UTC
Labels: bug
