### ISSUE TITLE
Add keyboard shortcuts Alt+Enter (file properties) and Alt+Home (go to gome dir)

### ISSUE THREAD

**Issue by Val6789** [lxqt/pcmanfm-qt#969] opened 2019-05-21 20:13 UTC
I suggest adding two keyboard shortcuts that are common in other file managers:

- Alt+Enter when a file is selected to open the Properties window
- Alt+Home to navigate to the home folder

##### Expected Behavior

I expect these shortcuts to work

##### Current Behavior

They don't

##### Possible Solution

Implement them

##### Steps to Reproduce (for bugs)

1. Press Alt+Home or Alt+Enter

##### Context

Keyboard shortcuts are useful to keyboard users

##### System Information
* Package version: pcmanfm-qt 0.14.1

**Comment by tsujan** [comment] 2019-05-21 20:23
> Current Behavior
> They don't

They do.

**Comment by Val6789** [comment] 2019-07-16 20:13
> > Current Behavior
> > They don't
> 
> They do.

I tried again and the two keyboard shortcuts don't work.

**Comment by tsujan** [comment] 2019-07-16 20:32
> I tried again and the two keyboard shortcuts don't work.

Then, they're used somewhere else. Find where and remove them.

**Comment by tsujan** [comment] 2019-07-16 20:38
Localization and not installing qt5-translations can be another cause.

**Comment by agaida** [comment] 2019-07-16 20:50
Do we have any tools that point to the application that react onto a certain keypress? Btw - alt enter don't work in debian too.

**Comment by agaida** [comment] 2019-07-16 21:00
ok - i guess i know the reason, but it is far to absurd - so i will let guess you - a  hint could be:

* Open lxqt-globalkeyshortcuts
* try to add a new shortcut
* press Alt + Enter
* (optional) use all the swearwords you know - in all languages you know.
* relax afterwards ....

**Comment by agaida** [comment] 2019-07-16 21:05
[](https://i.imgur.com/QhLeKva.png)

Best described with "God damn fuck, why the fuck behave it that way?".

**Comment by agaida** [comment] 2019-07-16 21:08
It turns out that god has nothing to do with:

```
agaida@ramme ~/work/code/pkg-main/pcmanfm-qt/snapshot (git)-[experimental-snapshots/latest] % grep -r Alt | grep Enter
pcmanfm/translations/pcmanfm-qt_da.ts:        <translation>Alt+Enter</translation>
pcmanfm/translations/pcmanfm-qt_cs.ts:        <translation>Alt+Enter</translation>
pcmanfm/translations/pcmanfm-qt_ar.ts:        <translation>Alt+Enter</translation>
pcmanfm/translations/pcmanfm-qt_nl.ts:        <translation>Alt+Enter</translation>
pcmanfm/translations/pcmanfm-qt_es.ts:        <translation>Alt+Enter</translation>
pcmanfm/translations/pcmanfm-qt_de.ts:        <translation>Alt+Enter</translation>
pcmanfm/translations/pcmanfm-qt_pt_BR.ts:        <translation>Alt+Enter</translation>
agaida@ramme ~/work/code/pkg-main/pcmanfm-qt/snapshot (git)-[experimental-snapshots/latest] % grep -r Alt | grep Return
pcmanfm/main-win.ui:    <string>Alt+Return</string>
pcmanfm/translations/pcmanfm-qt_da.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_en_GB.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_cs.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_cy.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_hu.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_hu.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_nb_NO.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_uk.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_uk.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_id.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_id.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_ca.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_ar.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_lt.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_lt.ts:        <translation>Alt+Return(Įvesti)</translation>
pcmanfm/translations/pcmanfm-qt_zh_CN.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_nl.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_es.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_ru.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_ru.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_gl.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_et.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_fr.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_it.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_sk_SK.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_sk_SK.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_el.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_el.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_de.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_zh_TW.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_pt.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_pt.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_ja.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_ja.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_tr.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_tr.ts:        <translation>Alt+Return</translation>
pcmanfm/translations/pcmanfm-qt_pt_BR.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_pl.ts:        <source>Alt+Return</source>
pcmanfm/translations/pcmanfm-qt_pl.ts:        <translation>Alt+Return</translation>
agaida@ramme ~/work/code/p
```

**Comment by agaida** [comment] 2019-07-16 21:10
I still not understand why someone change 'Return' to 'Enter' when enter is not a word in the target language ...

**Comment by agaida** [comment] 2019-07-16 21:16
```
pcmanfm/main-win.ui:    <string>Alt+Home</string>
pcmanfm/translations/pcmanfm-qt_de.ts:        <source>Alt+Home</source>
pcmanfm/translations/pcmanfm-qt_de.ts:        <translation>Alt+Pos1</translation>
```
btw Alt+Home works for me even translated

**Comment by agaida** [comment] 2019-07-16 21:29
We should change it in weblate - will close the issue again when merged.

**Comment by tsujan** [comment] 2019-07-16 22:29
@agaida Good catch! So, it was localization in your case.

We may also need to support both Alt+Enter` and `Alt+Return`.

**Comment by agaida** [comment] 2019-07-16 22:34
I guess this would be an upstream thing - we should do nothing about i guess - if upstream support alternative key-combination names - fine - if not we should not introduce.

**Comment by tsujan** [comment] 2019-07-16 22:43
When hard-coding a shortcut in an app, personally I prefer to add `Enter` when I add `Return` and conversely because, most of the time, they're used interchangeably.

That being said, it's likely that the problem you encountered isn't @Val6789's problem.

Here, `Alt+Enter` and `Alt+Home` work fine but I don't have localization and there's no other app consuming those shortcuts.

**Comment by agaida** [comment] 2019-07-16 23:13
We could ask him nicely :) - Btw - switching the translations back to Return works well - so it is in fact a translation problem here. What i don't get is the mechanism how the alt enter should work

The keyboard sends an Alt-Return in German and qttranslations5-l10n evaluate this - in simple words. How should the shortcut Alt-Enter work in this scenario?

**Comment by agaida** [comment] 2019-07-16 23:16
btw - what get you back if you create a new shortcut in lxqt-globalkeys ui when you hit <alt><enter>

**Comment by tsujan** [comment] 2019-07-16 23:23
Tomorrow I'll test it in both my system and VirtualBox.

**Comment by tsujan** [comment] 2019-07-17 00:16
OK, before I go to sleep (it's late here), in the following explanation, I put the names of physical keys in quotes and the name of shortcuts in backquotes (styled by markdown):

(1) `Qt::Key_Return` is usually shown by "Enter" in English keyboards, which is among the main keys.

(2) `Qt::Key_Enter` is the keypad "Enter", usually on the right side of the keyboard.

(3) The shortcut for showing file properties is `Alt + Return`, which means pressing "Alt" and the usual "Enter" in most English keyboards. In other words, `Alt + Return` is "Alt" + "Enter".

(4) When I press "Alt" and the usual "Enter" in lxqt-globalkeys, it means `Alt + Return`, as it should.

Now, to remove all confusions caused by names `Enter` and `Return` or their translations, we should treat the usual "Enter" (`Return`) and the keypad "Enter" (`Enter`) in the same way, as I suggested above. That means, we should add `Alt + Enter` in addition to `Alt + Return`, for showing properties.

However, the issue reported here wasn't about that (because of "Home").

**Comment by agaida** [comment] 2019-07-17 00:51
it was about both keys - just read the header and the description again - ok, the explanation you gave is good and i really remember only one program that handle alt return and alt enter different - it was a dtp program QuarkXpress - maybe some Adobe Programs differ too :)

**Comment by Val6789** [comment] 2019-07-17 05:58
I am using LXQt in french. In lxqt-config-globalkeyshortcuts, the shortcuts are recognized as Alt+Return and Alt+Home respectively. The corresponding lines in pcmanfm-qt_fr.ts are:

     <message>
        <location filename="../main-win.ui" line="265"/>
        <source>Alt+Up</source>
        <translation>Alt+Haut</translation>
    </message>
    <message>
        <location filename="../main-win.ui" line="277"/>
        <source>Alt+Home</source>
        <translation>Alt+Accueil (début)</translation>
    </message>

**Comment by agaida** [comment] 2019-07-17 08:07
@Val6789 - so we should change the translations - shortcuts have not to be translated :)

**Comment by tsujan** [comment] 2019-07-17 13:34
Made https://github.com/lxqt/pcmanfm-qt/pull/985 to prevent confusion about `Return` and "Enter".

**Closed** 2020-05-14 09:10 UTC
