### ISSUE TITLE
[Feature request] Please make possible disabling smooth scrolling for all views

### ISSUE THREAD

**Issue by Zeioth** [lxqt/pcmanfm-qt#1711] opened 2023-01-07 06:33 UTC
**Is your feature request related to a problem? Please describe.**
I have a 60hz 4K monitor and the scroll animations don't look very smooth. We already have an option to disable it, but it doesn't apply to all views.

**Describe the solution you'd like**
I'd like that the option apply to all views.

**Comment by tsujan** [comment] 2023-01-07 10:10
Duplicate of https://github.com/lxqt/pcmanfm-qt/issues/1564

**Closed by tsujan** 2023-01-07 10:10 UTC
