### ISSUE TITLE
Regression.  Places pannel has wrong font color

### ISSUE THREAD

**Issue by IMbackK** [lxqt/pcmanfm-qt#696] opened 2018-06-12 12:51 UTC
In PCManFM-Qt version 0.13.0 the font color in the places pannel backround was changed to be the window background color. The font color was retained as the content font color, making it unreadble in some themes.

**Comment by IMbackK** [comment] 2018-06-12 12:51
![screenshot_20180612_144717](https://user-images.githubusercontent.com/13803414/41291483-1a67211e-6e50-11e8-8761-406802ea4b45.png)

**Comment by PCMan** [comment] 2018-06-12 13:03
@tsujan I guess this issue is caused by the change here:
https://github.com/lxqt/libfm-qt/commit/6803d32a9e904f55ccaa42540952e101b76d18bf

**Comment by tsujan** [comment] 2018-06-12 13:14
I think the issue is in the theme/color scheme and should be seen in other places too.

@IMbackK, which theme do you use?

**Comment by tsujan** [comment] 2018-06-12 13:35
Qt's explanation about palettes (italics is mine):

"QPalette::Text → The foreground color used with Base. This is usually the same as the WindowText, in which case it must provide good contrast with *Window and Base*."

Logically, this doesn't mean that `QPalette::Text` and `QPalette::WindowText` (or `QPalette::Window` and `QPalette::Base`) should NOT have a high contrast with each other (because the word "usually" is used). However, the lack of high contrast is presupposed in several places. For example, symbolic SVG icons in KDE and LXQt only use `QPalette::WindowText`, so that they will be invisible in some places with a theme like that of the above screenshot.

**Closed** 2018-06-13 17:59 UTC
Labels: enhancement
