### ISSUE TITLE
Filter bar doesn't show up under certain circumstances

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#832] opened 2018-11-26 19:58 UTC
##### Expected Behavior

When   "permanent filter bar" is unset it should open when typing starts.
##### Current Behavior
It works only in freshly opened pcmanfm-qt windows or tabs, after changing to another folder typing highlights corresponding folder or files but doesn't open the  filter bar anymore.

##### Steps to Reproduce (for bugs)

1. open pcmanfm-qt with no permanent filter bar
2. start typing, filter bar appears
3. change folder, type
4. no bar opens anymore

##### System Information

up-to date git/arch linux

**Comment by tsujan** [comment] 2018-11-26 20:12
@stefonarch When you change the folder, the previous filter will be erased (that's an old behavior); so the filter-bar should (and does) disappear until you type another filter string. Is that what you meant?

**Comment by agaida** [comment] 2018-11-27 00:56
@stefonarch - to be honest - i can't reproduce it - maybe wrong build order or something missed?

**Comment by tsujan** [comment] 2018-11-27 07:01
> @stefonarch - to be honest - i can't reproduce it - maybe wrong build order or something missed?

If @stefonarch really meant that the bar didn't show up after typing, most probably, he inadvertently changed the focus to a widget other than the view, so that the typing wasn't done inside the view at all. But I don't know how.

@stefonarch, if that's not the case, please describe an exact way of reproducing the issue because it isn't reproducible in the way you mentioned. Closing for now.

**Comment by stefonarch** [comment] 2018-11-27 07:41
I rebuilt all components yesterday, repeating it now.
@tsujan there's no focus change, after entering a folder the pressed key highlights the name of a file instead of (re-)opening the bar. 

And I see now that switching displayed view reactivates the normal way for once.

**Comment by tsujan** [comment] 2018-11-27 07:51
@stefonarch 

Please tell me exactly what you do -- with all details -- so that I can repeat it here! In last months, I've changed folders and used filtering so many times but haven't encountered an issue. Maybe, what you do is very special, so that I've never done it.

**Comment by stefonarch** [comment] 2018-11-27 07:59
I rebuilt now and restarted the session. The "steps to reproduce" I wrote are the best I can tell..But  I notice a difference between using the enter key to open the selected folder or using the mouse click - with the enter key it works as it should. 
So just switching in some folder using   the mouse cursor and then typing produces the bug here always.

**Comment by tsujan** [comment] 2018-11-27 08:08
Unfortunately, I still can't reproduce it. I tried both double click and single click. To be very certain, I stopped pcmanfm-qt, downloaded its latest source from github, did `mkdir build && cd build` + `cmake ..` + `make` and run it from the build folder but the behavior was correct.

**Comment by tsujan** [comment] 2018-11-27 08:17
This video shows it: https://www.dropbox.com/s/1mmp8m8lrh059ug/pcmanfm-qt_filtering.mkv?dl=0

**Comment by stefonarch** [comment] 2018-11-27 08:35
Is maybe libfm related? Here's mine...
https://contadinoste.ocloud.de/index.php/s/euwEGnes5UWH0bV

**Comment by tsujan** [comment] 2018-11-27 08:59
Your video shows that your home is in the detailed mode but the folder you open is in the icon mode and is also among bookmarks. I did the same thing here (even chose the name "git" for the folder) but saw no problem: the filter-bar showed up correctly. What a mystery!

Yes, it can be related to libfm-qt. You could recompile and install the latest git version of libfm-qt and then recompile and install the latest pcmanfm-qt again to see what happens.

**Comment by tsujan** [comment] 2018-11-27 09:07
Wait a minute! I repeated my last test with the locally compiled pcmanfm-qt and the filter-bar didn't show up in home when it was customized to be in the detailed list mode!!

Reopened.

**Comment by tsujan** [comment] 2018-11-27 09:13
OK, the key for reproducing this was *the detailed list mode*: it only happens when the first folder is customized to be in the detailed list mode. Even so, it does not happen with my patched pcmanfm-qt. Therefore, something in my personal patch fixes the issue. Find the needle in the haystack...

**Comment by tsujan** [comment] 2018-11-27 10:17
@stefonarch Please test https://github.com/lxqt/pcmanfm-qt/pull/833 . I found and applied the difference between my personal patch and the git source. The logic is correct but tests are needed.

**Comment by stefonarch** [comment] 2018-11-27 17:07
Compiled and seems working fine now in all folders I tested.

**Closed** 2018-11-28 22:42 UTC
Labels: bug
