### ISSUE TITLE
Our RTL statusbar workaround may change statusbar height when its text changes

### ISSUE THREAD

**Issue by icf20** [lxqt/pcmanfm-qt#1207] opened 2020-10-13 11:26 UTC
i am using version 0.15.1

in compact view when i got two columns like

file_1  file_5
file_2  
file_3
file_4

if i select any file lest file from first column jump on top of the second

file_1  file_4
file_2  file_5
file_3

any idea if i have something badly configured

**Comment by tsujan** [comment] 2020-10-13 11:37
I can't reproduce the strange behavior your described; a selection change never affects the number of files in each column. There should be hidden factor in your case.

Could you attach (a link to) a video that shows the problem?

**Comment by icf20** [comment] 2020-10-13 11:45
![image](https://user-images.githubusercontent.com/17784575/95856199-efb81080-0d59-11eb-8357-4d58446454b8.png)

![image](https://user-images.githubusercontent.com/17784575/95856252-03fc0d80-0d5a-11eb-887a-e8ff98b43202.png)


i wonder if this is because of the theme selection coloring larger that expected

![image](https://user-images.githubusercontent.com/17784575/95856420-46bde580-0d5a-11eb-8b82-c387f4c99231.png)

**Comment by tsujan** [comment] 2020-10-13 11:53
> i wonder if this is because of the theme selection coloring larger that expected

Yes, the theme is the cause. Which theme is it?

NOTE: I close this because the behavior of the folder view is correct, but you could add comments.

**Comment by icf20** [comment] 2020-10-13 11:57
matcha-dark-aliz, if anyone google this and hame similar issue

**Comment by tsujan** [comment] 2020-10-13 12:04
> matcha-dark-aliz, if anyone google this and hame similar issue

You mean https://github.com/vinceliuice/Matcha-gtk-theme? That's a GTK theme. If so, you use Qt's `gtk2` style (check LXQt Appearance Configuration); don't you? And if that's the case, the gtk2 style should have a small problem: it may change the item height when the item is selected.

In short, the problem isn't in "Matcha" but in Qt's gtk2 style — if we call it "a problem" at all.

**Comment by tsujan** [comment] 2020-10-13 12:55
I checked your images in GIMP: The items where exactly at the same positions in your 2 screenshots. So, contrary to my above comment, the selection can't be the cause.

In the meanwhile, I also checked "Matcha-Dark-Aliz" belonging to Manjaro's `kvantum-theme-matcha-20190810-1-any.pkg.tar.xz`, which is a Kvantum theme. I couldn't reproduce the issue with it, although I tried hard. The gtk2 theme "matcha-dark-aliz" didn't produce any problem with Qt's gtk2 style either.

Reopening, until the hidden factor is found...

**Comment by tsujan** [comment] 2020-10-13 13:55
It took half an hour from me to see what could have been seen in a few minutes: The windows don't have the same height. I've put your screenshots beside each other with GIMP to show that clearly:

![windows](https://user-images.githubusercontent.com/981076/95869607-6d8b1480-0d78-11eb-84f5-825b1eb9e98f.png)

The darkness of the theme didn't let me see it at first.

For some reason, you've resized the window when you selected the item.

**Comment by icf20** [comment] 2020-10-13 14:24
i cant believe i installed OBS and recorded this 
https://imgur.com/uuQaJCP

**Comment by tsujan** [comment] 2020-10-13 14:28
> i cant believe i installed OBS and recorded this

Thanks for the video! It shows the same thing: For some reason, when you select the item, you also resize the window (make its height smaller — see how "Filter" moves upward in your video).

**Comment by icf20** [comment] 2020-10-13 14:28
the mouse does not resize the window

**Comment by tsujan** [comment] 2020-10-13 14:35
> the mouse does not resize the window

The **view** is definitely resized in your video. As far as I know, It can be resized only if the window is resized vertically.

Since I can't reproduce the problem here, take two screenshots of the whole window when an item is selected and when not. Compare them with each other. If the **windows** have the same size but the views don't, please attach the screenshots here because, in that case, we'll be dealing with a mystery.

**Comment by icf20** [comment] 2020-10-13 14:35
here another https://imgur.com/vvJRpuJ i had to learn how to record more that just the whole app in OBS

fml

**Comment by icf20** [comment] 2020-10-13 14:38
bspwm

**Comment by tsujan** [comment] 2020-10-13 14:39
OK. Please try a non-tiling window manager like Openbox (there are many others too) and see if the problem happens with it too.

**Comment by icf20** [comment] 2020-10-13 14:54
here is XFCE 

https://imgur.com/1T5XXKp

**Comment by tsujan** [comment] 2020-10-13 15:04
> here is XFCE

Thanks again.

In your last video, the window height doesn't change but the view height gets smaller with selection, so that there's no space for the the lowest item plus the margins. Therefore, the lowest item goes to the top of the next column. That's expected and there's no problem in it.

The real question is: why does the view height get smaller with selection? The next factor that comes to my mind is the font. Which font do you use and with which size? I want to install it here and try again.

**Comment by tsujan** [comment] 2020-10-13 15:12
Another question: do you use `qt5ct`?

**Comment by icf20** [comment] 2020-10-13 15:14
imo i found it the information bar at the bottom grow larger if a file is selected

![image](https://user-images.githubusercontent.com/17784575/95880147-7a5b3880-0d77-11eb-9337-726986d2ab6b.png)


yes i use qt5ct

**Comment by tsujan** [comment] 2020-10-13 15:18
> imo i found it the information bar at the bottom grow larger if a file is selected

That was why I asked about the font. Which font and with which size?

**Comment by icf20** [comment] 2020-10-13 15:24
the default sans 10 size

**Comment by tsujan** [comment] 2020-10-13 15:34
> the default sans

Which Sans? Your font doesn't seem to be DejaVu Sans, Bitstream Vera Sans, Noto Sans... (the character "7" isn't like them).

**Comment by icf20** [comment] 2020-10-13 15:43
![image](https://user-images.githubusercontent.com/17784575/95883567-6285b380-0d7b-11eb-84f1-57c93de3af7c.png)


i been changing allot of setting and so far i managed to not longer get the bump at my preferred resolution by using 22x22 icone size on pcmanfm-qt

**Comment by icf20** [comment] 2020-10-13 15:51
if i change the font for example to mono space the bump still happens

**Comment by tsujan** [comment] 2020-10-13 16:01
> if i change the font for example to mono space the bump still happens

That was the factor: Monospace :) I changed the fort to Monospace 10 and now, I can see the upward movement with all styles: Fusion, Breeze, Kvantum,..., with or without qt5ct.

I don't think this is a bug in pcmanfm-qt but will investigate it and reopen this page if a fix or workaround is found.

The problem is that the status bar height depends on its text with Monospace. It may even be a Qt issue.

**Comment by tsujan** [comment] 2020-10-13 16:30
I took a look at the code. The problem is triggered by the Unicode character `0x200E`, which is used to handle quotation marks. Once I replaced it with a usual quote, the movement disappeared with Monospace.

Should find the time to investigate it deeper. Until then, reopening...

**Comment by tsujan** [comment] 2020-10-13 16:43
FYI:

This is the old commit that triggers the problem with Monospace: https://github.com/lxqt/pcmanfm-qt/pull/606/files. It fixed RTL issues.

Whether that fix (or rather, workaround) should be sacrificed or not remains to be decided.

**Comment by icf20** [comment] 2020-10-13 20:12
i did follow that pull and the person who made it i hope hes ok ,no activity since covid-19 

---

i am happy that i found a extremely edge case :laughing: 

---

i let this here if the google gets more people, the probably of this happening on  a normal DE is extremely low is just few px that can be avoided by click and drag, also i noted that if i used 30px instead of 37px on polybar size this would not a issue or changed the split screen ratio in bspwm

**Comment by tsujan** [comment] 2020-10-13 20:17
@icf20 

I went back to the code just a few minutes before you wrote your last comment :) Good news: there's no need to that workaround anymore; the bug is fixed in Qt. I'm preparing a PR to reverse the workaround....

**Comment by tsujan** [comment] 2020-10-13 20:48
The fix is here: https://github.com/lxqt/pcmanfm-qt/pull/1209. RTL is OK too. Thanks for the report!

**Closed** 2020-10-14 17:33 UTC

**Comment by tsujan** [comment] 2020-10-14 17:59
@icf20 
In future, please don't close an issue that has an open PR. It'll be closed automatically when its PR is merged.
