### ISSUE TITLE
recent problems with mounting usb / mtp

### ISSUE THREAD

**Issue by gothmog123** [lxqt/pcmanfm-qt#734] opened 2018-07-19 06:04 UTC
Hi nowadays I'm experiencing some minor hiccups with mounting with pcmanfm-qt. Are these known issues?

When unmounting USB memory, I get "operation ended" and when trying to copy from a mounted MTP I get "operation unsupported". I can still copy using the command line.

**Comment by tsujan** [comment] 2018-07-19 11:17
After libfm-qt is made independent of libfm, some regressions happened and we're trying to identify and fix them. Please tell us about the problems you've encountered in a step-by-step way, so that we could reproduce and look into them. Thanks in advance!

**Comment by gothmog123** [comment] 2018-07-23 15:14
1. I plug in my usb memory, mount it with pcmanfm-qt/gvfs.

2. Do some operation like copying, etc.

3. When I'm finished I press the unmount icon.

4. I get "operation cancelled"

5. I press OK. There is not data loss, no adverse effects.

**Comment by tsujan** [comment] 2018-07-23 15:37
@gothmog123 The first issue is a duplicate of https://github.com/lxqt/pcmanfm-qt/issues/695 and fixed in https://github.com/lxqt/pcmanfm-qt/pull/725

As for the second issue, I'd tested and seen that copying from mobile to pcmanfm-qt worked OK; will test the converse later.

**Comment by tsujan** [comment] 2018-09-10 16:43
This problem should have been fixed by recent commits. Reopen if you still encounter it **with the latest git libfm-qt and pcmanfm-qt**.

**Closed by tsujan** 2018-09-10 16:43 UTC
