### ISSUE TITLE
'Free space' does not auto-refresh

### ISSUE THREAD

**Issue by DrinkDregs** [lxqt/pcmanfm-qt#1987] opened 2024-12-20 12:18 UTC
pcmanfm-qt 2.1.0

To reproduce:
Delete a sizeable file (e.g. 10GB) in pcmanfm-qt.

Expected:
The value of 'Free space' on the bottom-right changes automatically, like how the number of items on the bottom-left changes automatically.

Actual:
It doesn't change unless pcmanfm-qt is reloaded manually.

**Comment by isf63** [comment] 2024-12-20 12:31
I noticed this too.

>It doesn't change unless pcmanfm-qt is reloaded manually.

It updates once all relevant windows/tabs are closed (and one is reopened).

**Comment by tsujan** [comment] 2024-12-20 15:05
Yes, I know about it but have always forgotten to investigate it. Whether it's intentional or not, I'll look into it.

Thanks for reporting!

**Comment by tsujan** [comment] 2024-12-20 16:48
OK, I remembered everything. It's so by design.

Knowing the free space requires querying the filesystem info, and doing it with every file change would need extra I/O and CPU usage. Imagine transferring a huge number of files/folders. That takes a lot of I/O by itself, and we don't want to make it heavier than what it is. The app is supposed to be lightweight after all.

Technically speaking, the filesystem info is queried only on receiving the events `G_FILE_MONITOR_EVENT_CHANGED` and `G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED`, and only if the current directory is among the paths that should be updated. When we're inside a directory, that will happen if something about the directory itself has changed, not just its contents.

That being said, I leave the report open for now because I want to check whether, apart from theoretical considerations, querying the file system info has a real impact with HDDs. For that, I need to find time to test with my old laptop.

**Comment by tsujan** [comment] 2024-12-20 17:56
Tested it. There were lots of extra computations on transferring a great amount of files. They didn't have a tangible effect on my old laptop, but it's a powerful computer. And the effect could be tangible in the case of remote file systems.

So, it potentially contradicts lightness. The original author might have that in mind, and I agree with him.

**Comment by tsujan** [comment] 2024-12-20 20:21
Found a light way of doing it, after file jobs are done, and without touching libfm-qt. Reopening…

**Comment by tsujan** [comment] 2024-12-21 00:22
See https://github.com/lxqt/pcmanfm-qt/pull/1988#issuecomment-2557908181  for why this is impossible in a self-consistent way. Sorry, but that's a fact. Closing again.

**Closed by tsujan** 2024-12-21 00:22 UTC
Labels: enhancement
