### ISSUE TITLE
`Del` inside Trash doesn't work

### ISSUE THREAD

**Issue by ljgdasfhk** [lxqt/pcmanfm-qt#777] opened 2018-09-16 22:14 UTC
https://www.youtube.com/watch?v=McV9Sffd8B0

**Comment by tsujan** [comment] 2018-09-16 22:42
Doesn't happen with the latest git. Which version do you have?

**Comment by ljgdasfhk** [comment] 2018-09-17 08:47
> Doesn't happen with the latest git.

Не проверял, но сильно сомневаюсь, что "не наблюдается".
Версия из состава Archlinux : pcmanfm-qt 0.13.0-1
При попытке удаления файла в корзину pcmanfm-qt нагружает процессор на 100 %.

> closed

это надо понимать как "у нас все работает" ?

**Comment by tsujan** [comment] 2018-09-17 08:59
The "report" was useless enough; and now a comment in Russian?!

**Comment by agaida** [comment] 2018-09-17 15:12
> I have not checked it yet, but I strongly doubt that it "is not observed."
The version from the Archlinux: pcmanfm-qt 0.13.0-1
When you try to delete a file in the recycle bin, pcmanfm-qt loads the processor 100%.
This can be seen on the record. 

@tsujan - the reporter might be right - ok, its a bit sensless, but a bug in our trash handling. The important  difference is  that real users use our things. Easy to reproduce:
* Open pcmanfm-qt
* open trash
* mark a file and hit <Del> - a delete  dialog come up and try to move the file from trash to trash :dark_sunglasses: - last forever of course.
* <Shift><Del> works fine as expected

![](https://i.imgur.com/LGzo7QO.png)

**Comment by tsujan** [comment] 2018-09-17 15:27
@agaida OK, this is very different: your comment is a clear and complete bug report in English -- of course, because you care.

Yes, I can reproduce that. It's an important bug.

**Comment by agaida** [comment] 2018-09-17 15:37
@ljgdasfhk - hi, given that i had to learn the russian language in school thirty years ago and never used since it was not enough to translate your report - so please give us a chance and use google or another translator. Thats what i did :P thanks.

**Comment by agaida** [comment] 2018-09-20 21:13
@tsujan - just encountered without your current patch applied - same behaviour in remote filesystems. So disabling "Move to trash" for remote fs seems to be a good idea too.
![](https://i.imgur.com/g41rZKL.png)

**Comment by tsujan** [comment] 2018-09-21 01:28
Coming back to this:

@agaida Ignore my [last](https://github.com/lxqt/pcmanfm-qt/issues/777#issuecomment-423338076) comment! https://github.com/lxqt/pcmanfm-qt/pull/778 can be merged as it is (of course, if it works -- as it does here). The problem you found with remote filesystems should be fixed in libfm-qt and its fix seems easy: a `break` is missing :D I'll make another PR for it.

**Comment by tsujan** [comment] 2018-09-21 02:15
Here, in addition to https://github.com/lxqt/pcmanfm-qt/pull/778 : https://github.com/lxqt/libfm-qt/pull/277

I think I've also found a problem in GIO but it isn't important: trashed folders are reported to be non-deletable, although they can be deleted of course. As a result, `Delete` doesn't work with trashed folders; only `Shift+Delete` works. A workaround is possible but wouldn't have much usage.

**Closed** 2018-09-21 15:57 UTC
Labels: bug

**Comment by tsujan** [comment] 2018-09-22 15:42
@agaida A dangerous question: Is your SMB OK now? I can't see any problem in other places, although I may have illusion.

**Comment by agaida** [comment] 2018-09-22 18:50
Most things are o.k - a little but:
* Context menu shows move to trash (impossible on smb://) instead only delete
* Deletions work fine, but the current view in pcmanfm-qt isn't updated. (console shows, that now filemonitor can be created)

**Comment by tsujan** [comment] 2018-09-22 18:58
> Context menu shows move to trash

But "Move to Trash" offers deletion after being used; am I right?

Removing "Move to Trash" in such cases seems impossible with the current code (although, in theory, nothing's impossible) because moving to trash should be tried first and only if unsuccessful, deletion should be offered.

> but the current view in pcmanfm-qt isn't updated

That's OK because it's like `search://`: no file monitor can be created for SMB.

**Comment by agaida** [comment] 2018-09-22 19:29
yes to both

**Comment by tsujan** [comment] 2018-09-22 19:38
> is it possible to trigger an update of the view in such cases?

A file may be deleted/added from outside pcmanfm-qt and, because there's no file monitor, pcmanfm-qt wouldn't know about that in order to trigger a reload. Moreover, a reload can be expensive.

Does Nautilus or another GTK file manager update the view *without reloading*? I can't test because I don't have SMB.

**Comment by agaida** [comment] 2018-09-22 19:40
pcmanfm does - will test nautilus and dolphin

**Comment by tsujan** [comment] 2018-09-22 19:44
> pcmanfm does

That's more than enough -- no need to test Nautilus. It shows something is missing from libfm-qt. I'll look into it.
